### ISSUE TITLE
What should the behavior be when there is no repo?

### ISSUE THREAD

**Issue by jazzdelightsme** [AArnott/Nerdbank.GitVersioning#103]
Sometimes I'm a lurker, so rather than fork/clone a repo, I just click the "clone or download" button and choose to just download a .zip of a project.

When NBGV is used with such a project (such as NBGV itself), it doesn't work (build fails when at some point it tries to put together a System.Version object with a negative build component).

There's a tiny tweak that can be made to make it work... but maybe we want to do more than that: maybe we want to be able to handle this scenario, so we add a proper test for it; or maybe we want to add a better error that clearly says "hey there, you can't build this project if you don't have a .git...". Or maybe we want to somehow put the "there was no repo when this code was built" into the version information embedded in the binaries.

(I haven't really looked at the test code so I don't know but I suspect it could be a pain/significant change to simulate not having a repo.)

**Comment by AArnott** [comment]
Testing it should be easy. We have build integration tests including [one that should cover this scenario](https://github.com/AArnott/Nerdbank.GitVersioning/blob/d040da72dba53f203c123333ffcea9c3f5151878/src/NerdBank.GitVersioning.Tests/BuildIntegrationTests.cs#L93) that passes. I am looking into why it didn't catch this and will add a test for it in addition to accepting your PR.
