### ISSUE TITLE
Git height not calculated on built submodules

### ISSUE THREAD

**Issue by asherber** [AArnott/Nerdbank.GitVersioning#106]
I'm still trying to work out what's going on, and perhaps this use case is out of scope. But I wanted to report it here, for starters.

I have a couple of projects in their own dirs under a solution dir. The solution dir also has a folder called submodules, which contains a couple of git submodules. ProjA has a dependency on subProjB and subProjC, and all 3 use GitVersioning:
```
solution-dir
├───projA      
├───submodules         
│   ├───subProjB                      
│   ├───subProjC                   
```
When I build projA, the version info in the assembly is correct. But the version info in the subProjB and subProjC assemblies which get built and copied into the projA bin dir is not correct – they correctly pick up the base info from their own version.json, but the git height is 0 and the commit hash is the **hash of projA**.

The same thing happens if I open up `submodules/subProjB` directly in VS and build it, although of course it works fine if subProjB is off in its own folder somewhere else.

I can investigate this further when I have a few minutes.

**Comment by AArnott** [comment]
Interesting. It sounds like we agree on the expected behavior, but just to make sure:

subProjB and subProjC should build based on their own version.json and their own git height, such that their builds will be equivalent whether they appear as a submodule or a top-level module in someone's repo. 

Do you agree?

**Comment by asherber** [comment]
Yes, I agree.

Just to reiterate, the submodule projects do appear to be reading version.json correctly in terms of picking up major.minor. It's just the git height and commit hash that are incorrect when they are built from their submodule positions. And the git height for these submodule projects is always 0, I'm guessing because GitVersioning is failing to find a commit for the submodule's version.json in the superproject repo.

**Comment by asherber** [comment]
I think the issue is that the submodule doesn't have its own `.git` dir in the expected place, so `VersionOracle.OpenGitRepo()` keeps moving up the tree until it finds the `.git` dir of the superproject.

But the submodule does have a `.git` **file**, which gives the relative location of the correct `.git` folder:
```
gitdir: ../../.git/modules/submodules/subProjB
```
So I think what's needed is that `OpenGitRepo()` should also be looking for a `.git` file as it moves upwards, and if it finds it, and if the contents are as expected, it should use that path to locate the repo to use.

I've got some time tonight and will write up some sample code for this.

**Comment by AArnott** [comment]
Awesome. Thanks. Please feel free to send a PR.
Another thing to consider is that libgit2sharp didn't always support submodules. So it's _possible_ that we'll need to upgrade the version we use in NB.GV for this to work.
