### ISSUE TITLE
Preserve PATCH version in the version.json as an MSBuild property

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#115]
The scenario is that I'd like a mechanism to construct my File Version as `major.minor.patch.height` and package id's as `major.minor.patch-build.height`. This is so I can have more control over the patch version that goes out for packages/files/assemblies.

**Comment by onovotny** [comment]
@AArnott any guidance on what's needed here? I'd like to consider switching over to this but can't until this is resolved...

**Comment by AArnott** [comment]
I'll get it out today.

**Comment by AArnott** [comment]
I'm working on a more comprehensive feature to support this than what is currently in #119

**Comment by onovotny** [comment]
@AArnott Any updates or branches with your new comprehensive feature? Very much looking forward to trying it out :)

**Comment by AArnott** [comment]
Thanks for the ping. I got most of it working a couple weeks ago and had some of the tests updated/added then got side-tracked by my day job. :) I'll see if I can finish it today.
