### ISSUE TITLE
Automate the generation of version.txt and removal of assembly attributes when the package is installed

### ISSUE THREAD

**Issue by jkeech** [AArnott/Nerdbank.GitVersioning#12]
Remove the need to manually create a version.txt file and update AssemblyInfo.cs after the NuGet package is installed. By leveraging NuGet's Install.ps1 script, we should be able to automate this process by seeding the version.txt file with the Major.Minor from the AssemblyVersion attribute in AssemblyInfo.cs.

**Comment by sergey-shandar** [comment]
The problem with installation script is it runs every time NuGet is restored/updated etc. but a user expect this changes happen only once. Another problem with this, if someone doesn't like the tool and would like to uninstall it, uninstall script will not be able to revert the changes.

**Comment by jkeech** [comment]
It's not a problem, you just need to design the script so that it only creates the version.txt file (and removes assembly attributes) if a version.txt file doesn't already exist, that way it only runs on first install and no-ops during upgrades or if the user already had created the version.txt file manually.

Likewise, you can include an Uninstall.ps1 script which can reverse the vast majority of the logic: Delete version.txt, then add the AssemblyVersion attribute back into AssemblyInfo.cs using the Major.Minor from version.txt. This solves the 99% case. The other attributes (AssemblyFileVersion, AssemblyInformationalVersion) would need to be updated manually anyways after disabling this package, because they will have different file/informational versions and they need to ensure that the next version they produce is higher than the previous versions.

Your argument against automating these configuration steps is basically that you don't want NuGet to be modifying the project on behalf of the user, but that is one of the core features of NuGet and is well supported and expected behavior when installing packages. I think the benefit of making the package as easy to use as possible outweighs the downsides here. With the install script, I don't have to do any configuration whatsoever. I just install the package, commit the automated changes, and build.

**Comment by AArnott** [comment]
@jkeech said:
> our argument against automating these configuration steps is basically that you don't want NuGet to be modifying the project on behalf of the user, but that is one of the core features of NuGet and is well supported and expected behavior when installing packages. 

Actually, NuGet v3 deprecates .ps1 scripts and in the project.json world they're not supported at all. Ps1 scripts are infamous for not being adequately tested or working in all scenarios so they don't like them and discourage their use. So adding this at this point seems a little like swimming upstream. I do like having scripts that can automate it though, as this is typically a tedious process. And it does no harm to have the .ps1 script in the project.json world (they'll just be quietly ignored).

**Comment by AArnott** [comment]
I do *not* think that uninstalling the package should do the reverse of installing the package. That would produce too much unwanted churn during package upgrades.

**Comment by jkeech** [comment]
@aarnott, fair enough. I wasn't referring to the ps1 scripts specifically, but rather to the fact that NuGet is more than just a transport mechanism. It modifies projects to add assembly references and wire in props/targets files, so it has a history of automating useful tasks for users based on convention.
