### ISSUE TITLE
Incremental build after installing NB.GV fails due to generated assemblyinfo attribute collisions in .NET SDK projects

### ISSUE THREAD

**Issue by asherber** [AArnott/Nerdbank.GitVersioning#121]
I thought this scenario was now supported, but I may have misread. I have a .NET Standard class library in VS2017 targeting `netstandard1.4` and `net462`. When I install GitVersioning, I do not get a `project.json` file (have to add it manually), and when I build I get errors:
```
1>obj\Debug\net462\Foo.AssemblyInfo.cs(17,12,17,58): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
1>obj\Debug\net462\Foo.AssemblyInfo.cs(18,12,18,67): error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
1>obj\Debug\net462\Foo.AssemblyInfo.cs(21,12,21,54): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
```
Am I doing something wrong, or is this not supported yet?

**Comment by AArnott** [comment]
Yes, it's supported.

You should delete your project.json file. (new) VS2017 projects don't use it. Instead, when you install a package it adds a `PackageReference` item to your project file.

Your compile errors are due to https://github.com/dotnet/sdk/issues/1142. You can workaround it by deleting that temporary file manually. A "Rebuild" might do it.

**Comment by asherber** [comment]
Sorry, I meant that I don't get a `version.json` file -- I know that `project.json` shouldn't be there.

And yes, Rebuild does clear things up.

**Comment by AArnott** [comment]
In the new project type, installing packages never runs the package's install.ps1 script. So you have to create the version.json file yourself.

**Comment by AArnott** [comment]
I hardly hit this any more. I think they fixed it.
