### ISSUE TITLE
VS2017 Pack includes GitVersioning as a dependency in nupkg

### ISSUE THREAD

**Issue by asherber** [AArnott/Nerdbank.GitVersioning#122]
Is this a known issue?

![image](https://cloud.githubusercontent.com/assets/5248041/25307025/f8d45f6a-2767-11e7-9df0-554c3986f08c.png)

**Comment by AArnott** [comment]
Yes: https://github.com/NuGet/Home/issues/4125

In the meantime, just add `PrivateAssets="all"` to your `PackageReference` item.

**Comment by asherber** [comment]
I understand it might be out of scope for you, but it would be nice to have info about some of these gotchas in the GitVersioning docs, since the Core/Standard/VS2017 experience is so different from Framework/VSearlier. It would save people like me from asking all these questions!

**Comment by AArnott** [comment]
Very good point. The https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/nuget-acquisition.md doc hasn't been updated.

**Comment by asherber** [comment]
The correct syntax appears to be:
```xml
<PackageReference Include="Nerdbank.GitVersioning" Version="1.6.25">
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
```
(The comment above says `PrivateAssets="all"`and the doc page says `PrivateAssets="true"`.)

**Comment by AArnott** [comment]
Whoops. Thanks for catching. I fixed it to `all` instead of `true`. As for the child-element vs. attribute, both work with MSBuild 15.1.

**Comment by asherber** [comment]
I used the element, because that's what was first mentioned in the other thread you linked to. Now that I try it, I see that the attribute also works, although it's not one of the attributes suggested by IntelliSense. Makes me wonder if that usage is something undocumented that shouldn't be relied on. (The `PrivateAssets` element _is_ suggested by IntelliSense.)

**Comment by AArnott** [comment]
It definitely works by a reliable design: metadata can now be expressed as attributes. Intellisense is evidently lacking.
