### ISSUE TITLE
Switch NuGetPackageVersion to be based on SemVer2 when the nuget gallery is ready

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#126]
When NuGet/NuGetGallery#3547 is fixed, flip the `NuGetPackageVersion` property to be set to `SemVer2` instead of `SemVer1`. 
Either that or have some easy way to update it using an MSBuild prop. Goal is to make it easy to switch once NuGet supports it.

As [suggested by @onovotny](https://github.com/AArnott/Nerdbank.GitVersioning/pull/119#issuecomment-304738925).

**Comment by onovotny** [comment]
Given that support for this will be opt-in and require NuGet 4.3, some packages may wish to choose to use SemVer1 versions. The PR makes this it an option to use SemVer1 or SemVer2 as the package version string.
