### ISSUE TITLE
PowerShell scripts lock the directory

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#129]
If you run one of the PowerShell scripts `Get-Version.ps1`, the downloaded directory containing the script/dlls becomes locked as long as the powershell session is open. Cannot delete the directory.

Is there a way to unload the dll's or load them in another appdomain so they can be unloaded at the end of the script?

**Comment by Megadesty** [comment]
This doesn't seem to be GitVersioning specific, so does [something like this](https://stackoverflow.com/questions/1337961/powershell-unload-module-completely) help?

**Comment by onovotny** [comment]
Possibly, though I've switched to using the .NET Core tool version at the CLI, so that doesn't have those issues.

**Comment by Megadesty** [comment]
Sounds interesting, but could you elaborate a bit on this? Did you completely replace nbgv or just the part of getting the commit id corresponding to a specific version?

**Comment by onovotny** [comment]
I'm using nbgv but as a .net core cli tool now:

Here's how I set the cloud build number:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/Build/build.yml#L5-L15

And I get its data as a json object easily:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/Build/build.yml#L22

**Comment by AArnott** [comment]
This is because the powershell scripts load the assembly. Trying to script an appdomain to unload the assembly seems like quite a feat and the scenario already works by spawning the script via a child powershell process or using the nbgv CLI tool.
