### ISSUE TITLE
Add variables to cloudbuild

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#130]
There may be other reasons to use cloudBuild variables in a script, like needing to manually pack NuGet satellite assemblies. 

It'd be convenient if all of the variables calculated by NV.GV could be exposed, possibly prefixed -- NBGV_{variable}

**Comment by heaths** [comment]
I'm taking a look, but in the meantime you can work around this like so in at least one of your project files (as early as necessary during your build):

```xml
  <Target Name="SetAdditionalCloudBuildVars" DependsOnTargets="GetBuildVersion" BeforeTargets="SetCloudBuildVersionVars">
    <ItemGroup>
      <CloudBuildVersionVars Include="GitPackageVersion">
        <Value>$(PackageVersion)</Value>
      </CloudBuildVersionVars>
    </ItemGroup>
  </Target>
```
