### ISSUE TITLE
Version for satellite assemblies not generated correctly when using `dotnet build`

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#131]
When using NB.GV with a package that has satellite assemblies, the version numbers there are `0.0.0.0`

For a repro, see the `dev` branch of https://github.com/humanizr/Humanizer. This worked before using the regular SDK style `version` property.

Perhaps with SDK style projects, NB.GV shouldn't write its own `.Version.cs` file like it does today? It could just set the appropriate MSBuild properties and let the SDK style tasks generate the attributes in the assembly info file. That may fix the incremental build issue too.

**Comment by AArnott** [comment]
I'll take a look at your repro. I have dozens of projects with satellite assemblies and NB.GV does the right thing for all of them. 
For .NET SDK projects NB.GV still generates its own source file because the .NET SDK generated file doesn't support everything that NB.GV does. For example, the `ThisAssembly` generated class.

**Comment by onovotny** [comment]
Gotcha....at least, would it make sense to just have NB.GV add the "extra" stuff? Not a huge deal either way, but I did get bitten by having to add this line, https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Source/facades/Directory.build.props#L5 just for NB.GV. Seems like it should have respected the existing `GenerateAssemblyVersionAttribute` value?

**Comment by AArnott** [comment]
NB.GV already sets that property: https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/Nerdbank.GitVersioning.NuGet/build/Nerdbank.GitVersioning.targets#L28

But there is a bug in .NET SDK .targets' ability to restore packages and regenerate their file that causes issues.

**Comment by AArnott** [comment]
The .NET SDK bug is: https://github.com/dotnet/sdk/issues/1142

Yes, suppressing the generation of attributes by NB.GV and leveraging .NET SDK assembly info where possible would avoid the compile errors you were probably seeing. However, I suspect that would instead lead to a compiler success but that included stale attribute values given the bug I mention. So I think a build break is better than a defective build success.

**Comment by AArnott** [comment]
I'm guessing the satellite assembly issue is due to some non-standard thing you're doing -- or at least something I've never encountered. I'll investigate later today.

**Comment by onovotny** [comment]
What I did was go to go the Humanizer\src\Humanizer directory, then run `dotnet restore` then `dotnet build`. First time I've been able to use the CLI tools for building too :)

FWIW, I think the dotnet.exe version is 2.0.0 preview 1.

**Comment by AArnott** [comment]
Thanks. That's very helpful. I can repro the problem. I'll take a look at the logs and see what's going on.

**Comment by AArnott** [comment]
I observe that using msbuild.exe doesn't share the problem with the satellite assemblies. It only repros with dotnet.exe. Do you observe that too?

**Comment by onovotny** [comment]
Yes, I see the same thing now testing with `msbuild.exe`. Should I file this on the sdk repo or do you want to?

**Comment by AArnott** [comment]
It repros for me in at least one other of my projects when using dotnet.exe.

**Comment by AArnott** [comment]
I'll root cause it a bit more before we file a bug elsewhere.

**Comment by Bakanych** [comment]
Reproducing for vsts build solution task with csproj vnext. 
/obj/*AssemblyInfo.cs is cached with old version.
