### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#133]
The project has specific C# formatting choices like requiring `this.` for local property/member access. Having the preferred style specified in an `.editorconfig` can help VS and contributors do the right thing for the style you want.

**Comment by AArnott** [comment]
Good idea. Which version of VS shipped .editorconfig support? And how do I generate one?

**Comment by onovotny** [comment]
VS 2017 is the first one that ships with support. I believe most of the VS/.NET specific extensions are used/specified here: https://github.com/dotnet/roslyn/blob/master/.editorconfig

Mads also released a language service that has IntelliSense and highlighting for .editorconfig files: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig
