### ISSUE TITLE
Allow BuildNumberOffset to be overridden

### ISSUE THREAD

**Issue by robmen** [AArnott/Nerdbank.GitVersioning#136]
Today the build number offset is specified in the version file. In migrating to NB.GV, we've hit a complex scenario where part of our build needs one build number offset and in another pass the same projects need to be built with a different build number offset.

This feature request is to allow the build number offset to be overridden via a property in MSBuild.

The alternative we can think of right now is to modify the source version file during the build process. We definitely don't want to do that as it creates ordered dependencies in the build (that would majorly disrupt parallel build) and we'd have to clean the file up after every build.

**Comment by AArnott** [comment]
Why are you building the same projects twice with different versions?

**Comment by robmen** [comment]
The project has a series of `#ifdefs` that add increasing functionality. The DLL with "more" `#ifdefs` enabled needs to "win" since it provides more functionality. It's not an ideal system but we've threaded the needle on our side to meet all the requirements of a legacy system.

**Comment by AArnott** [comment]
What happens when you add one commit? Will your sequence of versions overlap with some of those produced by the prior commit?

**Comment by robmen** [comment]
No. We offset in the 10000s to minimize chance the height reaches 10000 commits and collides before we do another major.minor version. That gives us over 5 years to make 5 commits each day (which is more than we make) before needing to rev major.minor version.
