### ISSUE TITLE
Cake Build Addin Version

### ISSUE THREAD

**Issue by WilliamABradley** [AArnott/Nerdbank.GitVersioning#148]
Hi there,
I have noticed that your Tool is executed Via a Powershell script, which triggers various DLL Libraries.
Have you considering adding Cake Build Addin Support?

[Cake](https://cakebuild.net/) is a tool for automating building projects using C# and Roslyn (It stands for C# Make), it also accepts addins and tools via NuGet import, if your .dlls support .NET Core, it might be trivial to create a Cake Alias for it.
This way you can avoid Powershell, and allow for simple cross platform support.

**Comment by AArnott** [comment]
Which tool are you referring to? This project builds via msbuild, and is primarily invoked by other projects via msbuild. I do have a couple of powershell scripts meant for command line invocation just so folks understand what's going on, but they're not generally used programmatically as part of the build. And as every Windows developer has Powershell, and most do not have Cake, I'm not sure why I would want to replace the ps1 scripts with Cake.

That said, if you are aware of Cake-built projects that would like to leverage nerdbank.gitversioning, and if adding some kind of Cake support to NB.GV itself would help, I'd be interested in a PR if you want to contribute.

**Comment by WilliamABradley** [comment]
I'm not saying replacing the Powershell Script, but merely developing a Cake Alias Addin so that you don't have to call Powershell from Cake to invoke your Tool.

I am currently helping transition Microsoft/UWPCommunityToolkit to Cake with Microsoft/UWPCommunityToolkit#1440, and can currently call your script using a Powershell Addin.
This isn't the cleanest solution however, and prevents the build file from going cross platform.

An example of a Cake Addin script is the PowerShell Addin I use to use your file: https://github.com/SharpeRAD/Cake.Powershell
This uses C# to allow Cake to access Powershell functionality.

**Comment by WilliamABradley** [comment]
Oh ok, I see.
Adding Cake Addin support just allows you to call the Direct method after defining the preprocessor directive.

In this case it would be something like:
```
#addin "Nerdbank.GitVersioning"
```
then
```C#
var version = GetNerdbankGitVersion();
```

PowerShell may be cross platform, but it still has to be installed, Cake is clean, in that you don't have to install anything, it will download everything it needs to work.

**Comment by AArnott** [comment]
Ok, that seems interesting. I'll take a PR to enable that.

**Comment by AArnott** [comment]
@WilliamABradley Why close this? Is the need no longer applicable?

**Comment by WilliamABradley** [comment]
I realised that the only reason this was called in the Script was to check what version it would be, I thought this script actually performed changes to solution files or assemblies.
If you were going to add the Version Checking into cake, I can reopen it.

**Comment by AArnott** [comment]
I see. So the fact that msbuild when building the project already does the right thing makes direct Cake access less interesting? If so, then I guess closing is the right thing.

**Comment by WilliamABradley** [comment]
In Microsoft/UwpCommunityToolkit, this script is called by `Directory.Build.props` so the NuGet installation in the Build Script is just to add it to the .Nuget cache. `Directory.Build.props` I believe is collected by MSBuild for building projects, as it adds the information to the projects in that folder to combine the information.

From what I understand at least. That is what I could gather when I was reverse engineering it for my personal projects, as they use a .NET Standard project for UWP specific Code.
