### ISSUE TITLE
Cannot generate version.rc for static libraries

### ISSUE THREAD

**Issue by heaths** [AArnott/Nerdbank.GitVersioning#151]
The `Nerdbank.GitVersioning.Tasks.NativeVersionInfo` only supports EXE and DLL projects, but I need generated variables for a static lib included in both our app and test executables. We can set `VFT_STATIC_LIB` instead of `VFT_APP` or `VFT_DLL`. Also need to make sure the targets file supports `StaticLibrary`.

**Comment by heaths** [comment]
To note, this is currently blocked because lib.exe cannot link multiple .rc files. If you have a .lib with an .rc file, generating one like we do now fails the build.

**Comment by AArnott** [comment]
@heaths Didn't you mention a possible refactoring in how we do this so that it can work?

**Comment by heaths** [comment]
That wasn't the work around this issue, but to separate the .h and .rc files; however, I suppose if I did that and then just not link the .rc file and just require that anyone who wants to use the variables author their own `VS_VERSION_INFO` block that could work.

**Comment by heaths** [comment]
This was fixed similarly in another PR.
