### ISSUE TITLE
Fails within a git 'worktree'

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#152]
The experimental [git worktree](https://git-scm.com/docs/git-worktree) feature creates a checked out directory that doesn't have a .git folder, but rather a .git file that points to a folder within the .git folder in another directory. NB.GV should find that and work with it, if libgit2sharp supports it.

**Comment by asherber** [comment]
I haven't looked at this, but it seems like it would be similar to the code that was added to NB.GV to support submodules, which also use a `.git` file.

**Comment by AArnott** [comment]
libgit2sharp doesn't [support worktrees](https://github.com/libgit2/libgit2sharp/issues/1471) yet. So while I could code up a search for the .git file and open up the original repo, the checked out information that is so important would be wrong (since it wouldn't reflect the current work tree). So I think I'm blocked on libgit2sharp support.

**Comment by herebebeasties** [comment]
Looks like libgit2/libgit2sharp#1607 added support for worktrees back in December last year.
