### ISSUE TITLE
Automatically add PrivateAssets="All"

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#156]
I haven't tried this yet in my Extras, but I'm about to --

Rather than having people remember to add `PrivateAssets="all"` to the `PackageReference`, if the targets has this:
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.props#L53-L56

It can update the metadata automatically. There's no reason a user shouldn't have that for this package... ?

**Comment by onovotny** [comment]
This works for me upon testing it :)

**Comment by onovotny** [comment]
Hmm.... works for me for single target packages but fails for multi targeted ones. Haven't looked closer to see if there's a workaround.

**Comment by onovotny** [comment]
I've filed this too https://github.com/NuGet/Home/issues/6317

**Comment by AArnott** [comment]
Please post if this ends up working for multi-targeted projects.
