### ISSUE TITLE
How to increment the 'build' number with hotfixes

### ISSUE THREAD

**Issue by aalmada** [AArnott/Nerdbank.GitVersioning#158]
I'm using the git-flow branching model and successfully produced version 1.0.0 from master. Unfortunately I had to perform an hotfix that is now merged to master. I'd like to increment only the 'build' number to 1.0.1 as the API didn't change but the 'git height' seems to be 0. How to handle this case? Sorry but I couldn't find this case here in the issues.

**Comment by AArnott** [comment]
git height must increment if you add new commits. IIRC it's only 0 when you haven't yet committed your version.json file. Can you confirm you've done that?

**Comment by aalmada** [comment]
Using the Git Flow tool in SourceTree, I "started a new hotfix" branch, commited the fix and then "finished the hotfix", resulting in the merge of the new branch in "develop" and "master".

![2017-12-14 19_55_17-sourcetree](https://user-images.githubusercontent.com/534533/34014793-52b62aca-e114-11e7-8993-9ee744eeb5b5.png)

The Version.json file is the following:
```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.0",
  "nugetPackageVersion": {
    "semVer": 2
  },
  "publicReleaseRefSpec": [
    "^refs/heads/master$" 
  ]
}
```

**Comment by AArnott** [comment]
It sounds like you have a mini repo there with the repro. Can you share that out publicly so I can investigate? I would expect what you're expecting, I believe.

**Comment by aalmada** [comment]
This may have been related to #166
