### ISSUE TITLE
Git height set to 0 when version.json file has wrong capitalization

### ISSUE THREAD

**Issue by aalmada** [AArnott/Nerdbank.GitVersioning#166]
I can't make my VSTS CI use the Git height. I can't figure out what I'm missing.

The "Get sources" VSTS task has "Shallow fetch" unchecked.
I'm using a private build agent and I can see that the ".git" folder is present.  
The "dotnet pack" VSTS task has "Automatic package versioning" set to "Off".

![2018-01-25 15_34_54-datasonar net-ci summary](https://user-images.githubusercontent.com/534533/35397395-4456d5b2-01e7-11e8-8127-aa13d93f8a0c.png)

**GitVersioning:** 
v2.1.16
**Version.json:**
```JSON
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "1.1-alpha",
  "nugetPackageVersion": {
    "semVer": 2
  },
  "cloudBuild": {
    "setVersionVariables": true,
    "buildNumber": {
      "enabled": true
    }
  },
  "publicReleaseRefSpec": [
    "^refs/heads/master$" // we release out of master
  ]
}
```

**Comment by aalmada** [comment]
I see this in the logs:
```
2018-01-25T16:34:24.3416175Z ##[section]Async Command Start: Update Build Number
2018-01-25T16:34:24.3416442Z Update build number to 1.1.0-alpha+g8714f0f3ee for build 76
2018-01-25T16:34:24.3416585Z ##[section]Async Command End: Update Build Number
```

**Comment by AArnott** [comment]
Does it work from the local command line when you build? 
Can you build with the `/bl` switch and attach the binary log for inspection?

**Comment by aalmada** [comment]
![2018-01-26 08_35_02-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/534533/35431365-1559b81e-0274-11e8-8b8f-051235255041.png)

**Comment by aalmada** [comment]
Now the binary log: https://datasonarpknoa-my.sharepoint.com/:u:/g/personal/antao_almada_datasonar_io/EU-Syd0rYe5IpkCY1ZZ91DUB4k7qvcHgHjqw1vGnpIT3tQ?e=JSQXtk

**Comment by AArnott** [comment]
Thanks. So it looks like this repros whether in VSTS or local builds then. I can see from the binary log (thank you for including that) that NB.GV calculates a height of zero. The only time I've seen this is when `version.json` isn't actually committed into source control. Can you confirm that the version.json file you represented above is actually committed to your git repo and not just an untracked file you create before the build starts?

**Comment by aalmada** [comment]
Found the issue! It's case sensitive! The file was called "Version.json". Lowercasing the v makes it work.
I was rulling that out because the hash was being added to the version number.
Thanks for the help!

**Comment by AArnott** [comment]
Oh, wow. Nice catch. I'll chalk that up to when we read the current version, we just use the case-insensitive file system to find it, but when we search git history, we are now using git which _is_ case sensitive, so we can't find it and treat it like it isn't checked in.
