### ISSUE TITLE
NativeVersionInfo emits RC script in incorrect encoding

### ISSUE THREAD

**Issue by gundermanc** [AArnott/Nerdbank.GitVersioning#172]
Attempting to use Nerdbank.GitVersioning's NativeVersionInfo to generate non-version for native Windows DLLs can result in malformed version resources when special characters such as © and ® are used. Generally, the special character is preceded by an unprintable or garbage character.

**Crude Diagnosis:**
File.WriteAllText() writes text files in .NET's preferred UTF-8, no BOM, which I _think_ leads the output file to basically be RC's expected ANSI save for the rare multi-byte special character, which is rendered as two separate ANSI characters rather than a single 2 byte UTF-8 character.

I think there are at least three possible improvements:
1. Change ```Utilities.FileOperationWithRetry(() => File.WriteAllText(this.OutputFile, this.generator.GetCode()));``` to explicitly specify System.Text.ASCII, which looks to be the closest match. This comes with the possibility of losing characters altogether that are printable in UTF-8 but not ASCII, but would improve handling of common special characters like ©.
2. Use escape sequences to escape and insert any character that is more than one byte. I believe RC.exe supports some manner of escaping Unicode characters.
3. Write the RC script in UCS-2 encoding with BOM. My understanding is that Encoding.Unicode is a superset of UCS-2 such that all 2 byte UTF-16LE characters would render correctly and only 3 byte and larger characters would have to be escaped.

_Side note:_ Is there any reason for the strings being in Unicode to be conditional? Even if the application was compiled without Unicode support, I'd think there'd be no disadvantage to generating Unicode resources.

```
#if defined(_UNICODE) 
#define NBGV_VERSION_STRING(x) L ##x 
#else 
#define NBGV_VERSION_STRING(x) x 
#endif"; 
```

**Comment by AArnott** [comment]
@robmen contributed the C++ feature to NB.GV, including the [`#if _UNICODE`](https://github.com/AArnott/Nerdbank.GitVersioning/commit/03220ba6d7c1b0d3b684435a09bd57bda6e1a344#diff-fd48a11c28e965ebe509e0834003d90a) bit. Perhaps he can comment?

**Comment by robmen** [comment]
Honestly, the bulk of my RC knowledge comes from 1999 back when you had to build ANSI for Win9x separate from UNICODE for Windows2k.

Option 1 above makes a lot of sense to me. Switching to Unicode .rc files may be fine as well, as long as it still works when building the final output for ANSI (something we still do in old cases).

Note: I'm not going to be able to do the implementation and testing but if make a build with a solution, I can try it out on some of our older projects.

**Comment by gundermanc** [comment]
Assuming option 1 works I can probably make and contribute the fix. Should only be one line.

**Comment by AArnott** [comment]
I would hope we could get the Unicode encoding right if it would work. But if what it does now is broken and the 1-line fix makes it better, I'd accept a PR for that -- and wait for someone to complain that it isn't ideal, if in fact it can be better.

**Comment by heaths** [comment]
The Unicode option would probably be best. RC files in the modern era are supposed to be Unicode according to the VC++ team when I recently was trying to get VSCode to diff them right (more a problem with git itself, turns out).
