### ISSUE TITLE
Expose as a .NET Core Global tool

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#181]
As @onovotny suggested in [a PR comment](https://github.com/AArnott/Nerdbank.GitVersioning/pull/180#issuecomment-390307040), consider packaging NB.GV as a [.NET Core Global tool](https://natemcmaster.com/blog/2018/02/02/dotnet-global-tool/).

**Comment by onovotny** [comment]
Here's an updated blog that applies to 2.1 RC: https://natemcmaster.com/blog/2018/05/12/dotnet-global-tools/

**Comment by AArnott** [comment]
Any suggestions as to the command name? I'm leaning toward `nbgv`. 
Also, should it just be `nbgv` or `dotnet-nbgv` so that folks have to put `dotnet` first? I'm leaning toward just `nbgv`.

**Comment by onovotny** [comment]
I think just `nbgv`?

Questions are around what you do with it? Does it set environment variables? Does it return a json object that can be parsed? Does it set build server info? Maybe all of the above based on command line options?

**Comment by AArnott** [comment]
Yes, all those and more. I have it mostly written already.
Well, it doesn't set env vars. Pointless since it is its own process.
