### ISSUE TITLE
Cannot Build on master branch

### ISSUE THREAD

**Issue by clcrutch** [AArnott/Nerdbank.GitVersioning#185]
# Software
* Windows 10 1803 x64
* Visual Studio 2017 15.7.2
* Node.js 10.3.0
* PowerShell 5.1.17134.81
# Steps
1. From Developer Command Prompt for VS 2017, execute `PowerShell`
2. `./init.ps1`
3. `./build.ps1`
# Results
	  NerdBank.GitVersioning -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\netcoreapp1.0\NerdBank.GitVersioning.dll
	  NerdBank.GitVersioning -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\NerdBank.GitVersioning.dll
	  MSBuildExtensionTask -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\MSBuildExtensionTask\Debug\netcoreapp1.0\MSBuildExtensionTask.dll
	  MSBuildExtensionTask -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\MSBuildExtensionTask\Debug\net45\MSBuildExtensionTask.dll
	  Nerdbank.GitVersioning.Tasks -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\Nerdbank.GitVersioning.Tasks\Debug\net45\Nerdbank.GitVersioning.Tasks.dll
	  Nerdbank.GitVersioning.Tasks -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\Nerdbank.GitVersioning.Tasks\Debug\netcoreapp1.0\Nerdbank.GitVersioning.Tasks.dll
	  NerdBank.GitVersioning.Tests -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning.Tests\Debug\net452\NerdBank.GitVersioning.Tests.dll
	  NerdBank.GitVersioning -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\netcoreapp1.0\NerdBank.GitVersioning.dll
	  MSBuildExtensionTask -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\MSBuildExtensionTask\Debug\netcoreapp1.0\MSBuildExtensionTask.dll
	  Nerdbank.GitVersioning.Tasks -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\Nerdbank.GitVersioning.Tasks\Debug\netcoreapp1.0\Nerdbank.GitVersioning.Tasks.dll
	  Nerdbank.GitVersioning.NuGet -> C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\bin\Debug\Nerdbank.GitVersioning.NuGet\Nerdbank.GitVersioning.2.1.32.nupkg
	[20:53:43] Using gulpfile ~\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\gulpfile.js
	[20:53:43] Starting 'tsc'...
	[20:53:45] Finished 'tsc' after 1.43 s
	[20:53:45] Starting 'copyPackageContents'...
	[20:53:45] Finished 'copyPackageContents' after 8.13 ms
	[20:53:45] Starting 'setPackageVersion'...
	[20:53:45] 'setPackageVersion' errored after 480 ms
	[20:53:45] Error: Resolve-Path : Cannot find path 'C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nb
	gv.nuget\build\MSBuildFull\Validation.dll' because it does not exist.
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:14 char:42
	+ ... embly]::LoadFile((Resolve-Path "$DependencyBasePath\Validation.dll"))
	+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : ObjectNotFound: (C:\Users\Chris\...\Validation.dll:String) [Resolve-Path], ItemNotFoundE 
	   xception
		+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
	 
	Exception calling "LoadFile" with "1" argument(s): "Value cannot be null.
	Parameter name: path"
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:14 char:1
	+ $null = [Reflection.Assembly]::LoadFile((Resolve-Path "$DependencyBas ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
		+ FullyQualifiedErrorId : ArgumentNullException
	 
	Resolve-Path : Cannot find path 'C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nb
	gv.nuget\build\MSBuildFull\LibGit2Sharp.dll' because it does not exist.
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:16 char:42
	+ ... bly]::LoadFile((Resolve-Path "$DependencyBasePath\LibGit2Sharp.dll"))
	+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : ObjectNotFound: (C:\Users\Chris\...ibGit2Sharp.dll:String) [Resolve-Path], ItemNotFoundE 
	   xception
		+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
	 
	Exception calling "LoadFile" with "1" argument(s): "Value cannot be null.
	Parameter name: path"
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:16 char:1
	+ $null = [Reflection.Assembly]::LoadFile((Resolve-Path "$DependencyBas ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
		+ FullyQualifiedErrorId : ArgumentNullException
	 
	Resolve-Path : Cannot find path 'C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nb
	gv.nuget\build\MSBuildFull\Newtonsoft.Json.dll' because it does not exist.
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:17 char:42
	+ ... ]::LoadFile((Resolve-Path "$DependencyBasePath\Newtonsoft.Json.dll"))
	+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : ObjectNotFound: (C:\Users\Chris\...onsoft.Json.dll:String) [Resolve-Path], ItemNotFoundE 
	   xception
		+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
	 
	Exception calling "LoadFile" with "1" argument(s): "Value cannot be null.
	Parameter name: path"
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:17 char:1
	+ $null = [Reflection.Assembly]::LoadFile((Resolve-Path "$DependencyBas ...
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
		+ FullyQualifiedErrorId : ArgumentNullException
	 
	The following exception occurred while retrieving member "HelpFindLibGit2NativeBinaries": "Could not load file or 
	assembly 'LibGit2Sharp, Version=0.24.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333' or one of its 
	dependencies. The system cannot find the file specified."
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\tools\Get-Version.ps1
	:22 char:5
	+     [Nerdbank.GitVersioning.GitExtensions]::HelpFindLibGit2NativeBina ...
	+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [], ExtendedTypeSystemException
		+ FullyQualifiedErrorId : CatchFromBaseGetMember
	 

		at formatError (C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\node_modules\gulp\bin\gulp.js:169:10)
		at Gulp.<anonymous> (C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\node_modules\gulp\bin\gulp.js:195:15)
		at Gulp.emit (events.js:182:13)
		at Gulp.Orchestrator._emitTaskDone (C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\node_modules\orchestrator\index.js:264:8)
		at C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\node_modules\orchestrator\index.js:275:23
		at finish (C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\node_modules\orchestrator\lib\runTask.js:21:8)
		at C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\node_modules\orchestrator\lib\runTask.js:45:4
		at process._tickCallback (internal/process/next_tick.js:68:7)
	C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\build.ps1 : Build failure
		+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
		+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build.ps1
	 
	Node build failed
	At C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\build.ps1:41 char:13
	+             throw "Node build failed"
	+             ~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : OperationStopped: (Node build failed:String) [], RuntimeException
		+ FullyQualifiedErrorId : Node build failed

**Comment by AArnott** [comment]
Very curious, considering [appveyor follows those exact steps](https://github.com/AArnott/Nerdbank.GitVersioning/blob/ddc9486cf1ac8242f4bfab6990a79db9891b24e7/appveyor.yml#L30-L35) and [builds successfully](https://ci.appveyor.com/project/AArnott/nerdbank-gitversioning) (as can I).

https://github.com/AArnott/Nerdbank.GitVersioning/blob/ddc9486cf1ac8242f4bfab6990a79db9891b24e7/appveyor.yml#L25-L35

Given I can't repro it, I won't be able to do anything with this at least unless you can do some investigation into the first of the errors in your log:

> [20:53:45] Error: Resolve-Path : Cannot find path 'C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nb
gv.nuget\build\MSBuildFull\Validation.dll' because it does not exist.

Why doesn't it exist? Where did the build output go instead?

**Comment by clcrutch** [comment]
Here is a dir of the build directory.  Some files are there, but not all.

		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                MSBuildCore                                                           
	d-----         6/1/2018   4:31 PM                MSBuildFull                                                           
	-a----         6/1/2018   4:33 PM              0 files.txt                                                             
	-a----        5/31/2018   8:51 PM          13211 NerdBank.GitVersioning.targets                                        


		Directory: 
		C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSBuildCore


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                lib                                                                   
	-a----        5/31/2018   8:06 PM            256 LibGit2Sharp.dll.config                                               
	-a----         6/1/2018   4:30 PM          11776 MSBuildExtensionTask.dll                                              
	-a----         6/1/2018   4:30 PM           1900 MSBuildExtensionTask.pdb                                              
	-a----         6/1/2018   4:30 PM          57856 NerdBank.GitVersioning.dll                                            
	-a----         6/1/2018   4:30 PM         189952 NerdBank.GitVersioning.pdb                                            
	-a----         6/1/2018   4:30 PM          43008 Nerdbank.GitVersioning.Tasks.dll                                      
	-a----         6/1/2018   4:30 PM          11356 Nerdbank.GitVersioning.Tasks.pdb                                      


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                linux                                                                 
	d-----         6/1/2018   4:31 PM                osx                                                                   
	d-----         6/1/2018   4:31 PM                win32                                                                 


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib\linux


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                x86_64                                                                


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib\linux\x86_64


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM        1199561 libgit2-1196807.so                                                    


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib\osx


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM        1727112 libgit2-1196807.dylib                                                 


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib\win32


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                x64                                                                   
	d-----         6/1/2018   4:31 PM                x86                                                                   


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib\win32\x64


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM        1141248 git2-1196807.dll                                                      
	-a----        5/31/2018   8:06 PM        9859072 git2-1196807.pdb                                                      


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildCore\lib\win32\x86


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM         856576 git2-1196807.dll                                                      
	-a----        5/31/2018   8:06 PM        9785344 git2-1196807.pdb                                                      


		Directory: 
		C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSBuildFull


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                lib                                                                   
	-a----        5/31/2018   8:06 PM            256 LibGit2Sharp.dll.config                                               
	-a----         6/1/2018   4:30 PM           7168 MSBuildExtensionTask.dll                                              
	-a----         6/1/2018   4:30 PM            944 MSBuildExtensionTask.pdb                                              
	-a----         6/1/2018   4:30 PM          57856 NerdBank.GitVersioning.dll                                            
	-a----         6/1/2018   4:30 PM         192000 NerdBank.GitVersioning.pdb                                            
	-a----         6/1/2018   4:30 PM          47104 Nerdbank.GitVersioning.Tasks.dll                                      
	-a----         6/1/2018   4:30 PM          11596 Nerdbank.GitVersioning.Tasks.pdb                                      


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                linux                                                                 
	d-----         6/1/2018   4:31 PM                osx                                                                   
	d-----         6/1/2018   4:31 PM                win32                                                                 


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib\linux


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                x86_64                                                                


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib\linux\x86_64


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM        1199561 libgit2-1196807.so                                                    


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib\osx


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM        1727112 libgit2-1196807.dylib                                                 


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib\win32


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	d-----         6/1/2018   4:31 PM                x64                                                                   
	d-----         6/1/2018   4:31 PM                x86                                                                   


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib\win32\x64


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM        1141248 git2-1196807.dll                                                      
	-a----        5/31/2018   8:06 PM        9859072 git2-1196807.pdb                                                      


		Directory: C:\Users\Chris\Repos\misc\Nerdbank.GitVersioning\src\nerdbank-gitversioning.npm\out\nbgv.nuget\build\MSB
		uildFull\lib\win32\x86


	Mode                LastWriteTime         Length Name                                                                  
	----                -------------         ------ ----                                                                  
	-a----        5/31/2018   8:06 PM         856576 git2-1196807.dll                                                      
	-a----        5/31/2018   8:06 PM        9785344 git2-1196807.pdb

**Comment by clcrutch** [comment]
If my understanding is correct, it looks like the NuGet project is supposed to copy the files for the npm build, but it doesn't seem to be copying all of the files when I execute `build.ps1`.  In fact, the nupkg that is generated, also appears to be lacking files for some reason.

It appears as if the build directory for NerdBank.GitVersioning has the missing files.


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	d-----        5/31/2018   8:48 PM                lib                                                                                  
	-a----         6/1/2018   6:51 PM              0 files.txt                                                                            
	-a----        5/31/2018   8:06 PM         397312 LibGit2Sharp.dll                                                                     
	-a----        5/31/2018   8:06 PM            256 LibGit2Sharp.dll.config                                                              
	-a----        5/31/2018   8:48 PM          57856 NerdBank.GitVersioning.dll                                                           
	-a----        5/31/2018   8:48 PM         192000 NerdBank.GitVersioning.pdb                                                           
	-a----        5/31/2018   8:48 PM          84540 NerdBank.GitVersioning.xml                                                           
	-a----         4/2/2017   5:46 PM         652288 Newtonsoft.Json.dll                                                                  
	-a----        8/14/2016   6:52 PM          15872 Validation.dll                                                                       


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	d-----        5/31/2018   8:48 PM                linux                                                                                
	d-----        5/31/2018   8:48 PM                osx                                                                                  
	d-----        5/31/2018   8:48 PM                win32                                                                                


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib\linux


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	d-----        5/31/2018   8:48 PM                x86_64                                                                               


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib\linux\x86_64


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	-a----        5/31/2018   8:06 PM        1199561 libgit2-1196807.so                                                                   


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib\osx


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	-a----        5/31/2018   8:06 PM        1727112 libgit2-1196807.dylib                                                                


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib\win32


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	d-----        5/31/2018   8:48 PM                x64                                                                                  
	d-----        5/31/2018   8:48 PM                x86                                                                                  


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib\win32\x64


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	-a----        5/31/2018   8:06 PM        1141248 git2-1196807.dll                                                                     
	-a----        5/31/2018   8:06 PM        9859072 git2-1196807.pdb                                                                     


		Directory: C:\Users\Chris\Repos\clcrutch\Nerdbank.GitVersioning\bin\NerdBank.GitVersioning\Debug\net45\lib\win32\x86


	Mode                LastWriteTime         Length Name                                                                                 
	----                -------------         ------ ----                                                                                 
	-a----        5/31/2018   8:06 PM         856576 git2-1196807.dll                                                                     
	-a----        5/31/2018   8:06 PM        9785344 git2-1196807.pdb                                                                     




[Nerdbank.GitVersioning.2.1.32.zip](https://github.com/AArnott/Nerdbank.GitVersioning/files/2064580/Nerdbank.GitVersioning.2.1.32.zip)

**Comment by AArnott** [comment]
It now repros on my box too, interestingly.

**Comment by AArnott** [comment]
And it repros on appveyor now too. In the last 5 days something changed. I wonder if it was a VS 2017 servicing release...
