### ISSUE TITLE
pre-release label for NPM packages not working

### ISSUE THREAD

**Issue by luizgrs** [AArnott/Nerdbank.GitVersioning#187]
The pre-release label I'm setting in version.json is being ignored and replaced by the git commit when trying to stamp a NPM package. Is this the expected behavior? I've successfully used very similar version.json for nuget packages in another projects and it works fine.

# Software
NPM 6.1.0
Node 10.4.0
Powershell 5.1.16299 .431
nerdbank-gitversioning 2.1.7

### version.json
```
   {
        "version": "2.1-alpha", // required
   }
```

### check-version.js
```
    var nbgv = require('nerdbank-gitversioning');
    nbgv.getVersion().then(e => console.log(e));
```

### node .\check-version.js
> { cloudBuildNumber: '2.1.0+ga1b9651eef',
>   cloudBuildNumberEnabled: false,
>   buildMetadataWithCommitId: '{ga1b9651eef}',
>   assemblyVersion: '2.1.0.0',
>   assemblyFileVersion: '2.1.0.47521',
>   assemblyInformationalVersion: '2.1.0+ga1b9651eef',
>   publicRelease: false,
>   simpleVersion: '2.1.0',
>   buildNumber: '0',
>   majorMinorVersion: '2.1',
>   gitCommitId: 'a1b9651eef6e237e30a47c233efef59e22869b7a',
>   gitCommitIdShort: 'a1b9651eef',
>   versionHeight: '0',
>   versionHeightOffset: '0',
>   version: '2.1.0.47521',
>   cloudBuildVersionVarsEnabled: true,
>   cloudBuildVersionVars:
>    '{[GitAssemblyInformationalVersion, 2.1.0+ga1b9651eef], [GitBuildVersion, 2.1.0.47521], [GitBuildVersionSimple, 2.1.0]}',
>   buildMetadata: '{}',
>   buildMetadataFragment: '+ga1b9651eef',
>   nuGetPackageVersion: '2.1.0-ga1b9651eef',
>   npmPackageVersion: '2.1.0-ga1b9651eef',
>   semVer1: '2.1.0-ga1b9651eef',
>   semVer2: '2.1.0-ga1b9651eef',
>   semVer1NumericIdentifierPadding: '4' }

**Comment by luizgrs** [comment]
I was working in a new branch still not pushed to the remote origin, so all commits (4) were still local.

After pushing them the version is now correct: Setting package version to 2.0.0-alpha-gfc00cfa630

**Comment by AArnott** [comment]
This doesn't repro for me either. 

Note that *pushing* commits is irrelevant. NB.GV only ever looks at the local commits in a repo. I can't explain why you only saw it work after pushing, but when I tried today I saw the -prerelease suffix I added only worked after committing the change (but before pushing).
