### ISSUE TITLE
nbgv cloud variables

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#193]
Add options to set basic cloud build variables as well as "all" variables.
Alternatively, just do what is specified in version.json file, perhaps.

**Comment by onovotny** [comment]
I think the scenario here should be to remove the need for a dummy project or a special project as described here:
https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md#set-cloud-build-variables-from-just-one-project

The default version.json wouldn't have any cloud build numbers enabled, but a user could call the nbgv command in the build script.

It can set the default CloudBuildNumber, override that with -v (works today). New, to add, it can do the set cloud vars and set all vars. 

Open question is what the default should be. Any reason not to set everything and have opt-out options?

**Comment by onovotny** [comment]
Not sure if I'm using it wrong, but it's not detecting/setting the version correctly:

https://dotnetfoundation.visualstudio.com/Humanizer/_build/results?buildId=2573&view=logs

I'm using it here:
https://github.com/Humanizr/Humanizer/blob/c650922298c22a2c6739debbb1d2fa870bba0fcd/.vsts-shared.yml#L13

I've tried it with and without specifying the working directory (where the version.json is)

**Comment by AArnott** [comment]
Given the version.json already influences the version and can specify whether all cloud build variables are set (even if overall it is not enabled) how about the default being what the json prescribes?

**Comment by onovotny** [comment]
Fair enough, though that makes it a bit non-deterministic from looking only at the command line params. I don't know how it feels to have the default options controlled by that, which could easily be different per project. 

It seems lie the command line should be explicit one way or the other?

**Comment by AArnott** [comment]
I found the bug that prevented `nbgv cloud` from writing out the version, causing your build failure, @onovotny. I have a fix that will be included in this feature request.

**Comment by AArnott** [comment]
Fix is now published to nuget.org as v2.1.65
