### ISSUE TITLE
Prerelease Nerdbank.GitVersioning package isn't in AppVeyor's feed

### ISSUE THREAD

**Issue by Megadesty** [AArnott/Nerdbank.GitVersioning#202]
After I created PullRequest #201 and the [Build](https://ci.appveyor.com/project/AArnott/nerdbank-gitversioning/build/2.1.68+g3cc15e5a32) run, I expected the new package version `2.1.68-g3cc15e5a32` in the [feed](https://ci.appveyor.com/nuget/nerdbank-gitversioning/FindPackagesById()?id=%27Nerdbank.GitVersioning%27&$filter=IsPrerelease&$orderby=Version%20desc), but it's not there (and it seems that many other versions from last time are also missing).

**Comment by AArnott** [comment]
That's because appveyor doesn't publish packages from PRs:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/dab57f2e00bdc8be9c8bfc694b8babdf01c29bbc/appveyor.yml#L12-L13

**Comment by Megadesty** [comment]
That sounds like this is intended? Then I find the contribution documentation is a bit misleading:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/dab57f2e00bdc8be9c8bfc694b8babdf01c29bbc/CONTRIBUTING.md#L58-L59

**Comment by AArnott** [comment]
Ah yes, that was behavior we used to have. I'll update the docs--thanks for pointing this out.
