### ISSUE TITLE
Put more information into Assembly's Product Version field

### ISSUE THREAD

**Issue by Megadesty** [AArnott/Nerdbank.GitVersioning#203]
Me again, sorry for flooding, but GitVersioning is so nice and I introduce it now in every project! :)

This time I have a feature request:
As a developer/maintainer/service hotline employee I would like to have all possible information I can get about my product in the scenario when it's installed on a customer's computer and the customer has any problem with my software, so that I can better/faster see what's going wrong. Especially I'm interested in the following information:

- _Build-ID_: Every assembly built and deployed by an official cloud build server should have one so that I can see which build produced that binary, but can also identify "illegal" assemblies built by a developer locally on his machine and deployed manually. As far as I know every cloud build system populates the current BuildID via an environment variable, in VSTS we have `$(BuildID)`
- Used _Configuration_ and _Platform_
- _Timestamp_ of the build

So an example Product Version would be: `1.7.25+gd74e823c0a Build 65122 Release|Any CPU 2018/07/31 14:45:00`

Every extra information in Product Version is configurable in version.json, e.g.
```json
{
  "version": "1.7",
  "assemblyProductVersion": {
    "includeBuildId": true,
    "includeConfiguration": true,
    "includePlatform": true,
    "includeTimestamp: true
  }
}
```
The whole section as well as any specific 'include' can be omitted, default is `false`.

Now I would like to know
- is it correct, that this is not possible today? (maybe I'm overlooking something)
- is such a requirement justified?
- feasible?
- if I work on a Pull Request, any tips or tricks which would help me?

Thanks for feedback, also for the awesome library itself.

**Comment by AArnott** [comment]
> Used Configuration and Platform

This information should already be available. By default, a compilation will include the `AssemblyConfigurationAttribute` that indicates in a compiled assembly which configuration was used:

```cs
[assembly: AssemblyConfiguration("Debug")]
```

> Build-ID
> Timestamp of the build

Including these two would violate the first priority of this project. From the README.md file: "Prioritize absolute build reproducibility. Every single commit can be built and produce a unique version." Including these values would mean that each build produces a different version and break reproducibility. While it's certainly feasible to include it, I don't think it's appropriate for NB.GV to include it as a built-in feature. 

But I'd like to unblock you if possible. You can create `BuildMetadata` MSBuild items to store these values which will get them included in the `AssemblyInformationalVersion`. For example:

```xml
<ItemGroup>
  <BuildMetadata Include="$(Build_BuildId)" />
</ItemGroup>
```

**Comment by Megadesty** [comment]
It's brilliant that what I want works already out of the box, even if it breaks the rule of reproducibility. I will discuss it with the teams, for now I am unblocked (thanks a lot!) with the following solution:
```xml
<PropertyGroup>
  <VersionBuildMetadata>$([System.DateTime]::Now.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH'-'mm'-'ss'-'fff'Z'"))</VersionBuildMetadata>
  <VersionBuildMetadata Condition="'$(Configuration)' == 'DEBUG'">$(VersionBuildMetadata).Debug</VersionBuildMetadata>
  <VersionBuildMetadata Condition="'$(Configuration)' == 'RELEASE'">$(VersionBuildMetadata).Release</VersionBuildMetadata>
  <PlatformBuildMetadata Condition="'$(Platform)' != ''">$([System.String]::Copy("$(Platform)").Replace(" ",""))</PlatformBuildMetadata>
  <PlatformBuildMetadata Condition="'$(Platform)' == ''">AnyCPU</PlatformBuildMetadata>
  <VersionBuildMetadata>$(VersionBuildMetadata).$(Platform)</VersionBuildMetadata>
  <Build_BuildId Condition="'$(Build_BuildId)' == ''">0</Build_BuildId>
  <VersionBuildMetadata>$(VersionBuildMetadata).BuildId-$(Build_BuildId)</VersionBuildMetadata>
</PropertyGroup>

<ItemGroup>
  <BuildMetadata Include="$(VersionBuildMetadata)"></BuildMetadata>
</ItemGroup>
```
This creates versions like `2.3.7+g7a031e41f0.2018-08-09T13-20-23-417Z.Release.AnyCPU.BuildId-65959`
