### ISSUE TITLE
Use build ID from VSTS as build number

### ISSUE THREAD

**Issue by jobanputra** [AArnott/Nerdbank.GitVersioning#206]
My builds are hosted on VSTS. I see how to override the build ID on VSTS with build number (git height) calculated by NB.GV. 
However I want to go the other way around. How do I configure my `version.json` file to use the build ID environment variable (`Build.BuildId`) as the build number (instead of the git height)?

**Comment by AArnott** [comment]
That goes contrary to a tenet of nb.gv, which is reproducibility of builds and versions. Why would you want this?

**Comment by jobanputra** [comment]
Yes. I read that one of your motivations was the exact opposite. Our case was to pull this information out of a crash dump and get back to the exact build. However I think we should be able to do it using the git commit id.

**Comment by AArnott** [comment]
Thank you for the use case info.
