### ISSUE TITLE
dotnet pack doesn't respect public releases

### ISSUE THREAD

**Issue by llehn** [AArnott/Nerdbank.GitVersioning#220]
I guess this is a similar issue to https://github.com/AArnott/Nerdbank.GitVersioning/issues/155

when I use `dotnet pack` on a master it creates a package with the commit suffix, although version.json contains:
`"publicReleaseRefSpec": [
    "^refs/heads/master$", // we release out of master
    "^refs/tags/v\\d+\\.\\d+" // we also release tags starting with vN.N
  ],`

I run dotnet pack within a linux docker image where I can't call msbuild.exe. Its not clear to me how to create a nuget package with a public version.

**Comment by AArnott** [comment]
`dotnet pack` works perfectly for me and I use it across a lot of repos and CI servers.

Can you add a `git branch` command immediately before your `dotnet pack` command in your build script and report on the output?

**Comment by llehn** [comment]
It does work in a bare repo. 
It does not work in a "working repo" somehow (which I tested first), which is irrelevant to me.

**Comment by llehn** [comment]
Now it works, weird
