### ISSUE TITLE
Git hash being shown on master in CI

### ISSUE THREAD

**Issue by daniel-sherwood** [AArnott/Nerdbank.GitVersioning#221]
Hi

If I do a build on my PC, then the version is correctly shortened to v0.1.13, however performing the same build in GitLab CI with a docker runner includes the git hash as shown below.

`Creating RPM package C:\Users\djs2\Documents\Projects\p2099\git\client_side_server_components_master\src\NodeHosts\BackendHost\bin\Debug\netcoreapp2.1\linux-x64\Backend.0.1.143.linux-x64.rpm`

`Creating RPM package /builds/p2099/server-components/src/NodeHosts/BackendHost/bin/Debug/netcoreapp2.1/linux-x64/Backend.0.1.143-g021fe666ce.linux-x64.rpm
`
What is likely to cause this behaviour?

Cheers

**Comment by AArnott** [comment]
See #220
