### ISSUE TITLE
Add cake-contrib user to Cake.GitVersioning NuGet package

### ISSUE THREAD

**Issue by gep13** [AArnott/Nerdbank.GitVersioning#234]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by AArnott** [comment]
The blog post answers most of my questions. The only remaining questions are regarding the security of the `cake-contrib` account. 
1. Is 2FA turned on?
1. How are the credentials protected? 
1. How many people have access?
1. What qualifications are demanded of people before they gain access to that account?

**Comment by AArnott** [comment]
Yes, that addresses my concerns. Thank you. I've added `cake-contrib` as a package owner.

**Comment by gep13** [comment]
>@AArnott said...
Yes, that addresses my concerns. Thank you. I've added cake-contrib as a package owner.

Thank you very much!  I have accepted the request to be added as a package owner.
