### ISSUE TITLE
npm setPackageVersion semver2 support

### ISSUE THREAD

**Issue by cdunford** [AArnott/Nerdbank.GitVersioning#236]
setPackageVersion is a nice helper function to update the version in a package.json file. Today it looks like it will always spit out a semver1 version. It would be nice if it could be parameterized to support semver2, as npm as semver2 support.

**Comment by AArnott** [comment]
Does NPM support semver2 consistently everywhere, or should it be an option for folks to use semver1 or 2? And which should be the default.

**Comment by AArnott** [comment]
I'm finding semver2 usage as far back as six years ago [here](https://www.npmjs.com/package/lodash/v/0.5.0-rc.1) (history page). So it sure seems like semver2 should be the default (and in fact only) option.
