### ISSUE TITLE
is it possible to update LibGit2Sharp package version from 0.25.2 to 0.26.0-preview-0054?

### ISSUE THREAD

**Issue by pmunshi007** [AArnott/Nerdbank.GitVersioning#240]
Actually I am facing issues while building my application which uses Nerdbank.gitVersioning on CentOS docker container because of LibGit2Sharp library. I am receiving multiple errors as below 
```
/root/.nuget/packages/nerdbank.gitversioning/2.2.13/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL '/root/.nuget/packages/nerdbank.gitversioning/2.2.13/build/lib/linux/x86_64/libgit2-6311e88.so': The specified module or one of its dependencies could not be found.
 /root/.nuget/packages/nerdbank.gitversioning/2.2.13/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init() 
/root/.nuget/packages/nerdbank.gitversioning/2.2.13/build/Nerdbank.GitVersioning.targets(63,5): error MSB4018:    at Nerdbank.GitVersioning.GitExtensions.OpenGitRepo(String pathUnderGitRepo) 
```
I tried to resolve issue by building LibGit2Sharp binaries on CentOS but as per the conversation on https://github.com/libgit2/libgit2sharp.nativebinaries/issues/78 issue I was heading towards wrong direction. 

I guess the new preview version of LibGit2Sharp (0.26.0-preview-0054) works fine with CentOS as per my conversation on above issue. Is it possible to updated this package version soon in next release for  Nerdbank.GitVersioning repository? 

Your help and support would be really appreciated. I am stuck with this issue since last 2 days.

**Comment by AArnott** [comment]
This exact upgrade is already in progress, and tracked by https://github.com/AArnott/Nerdbank.GitVersioning/issues/228.
