### ISSUE TITLE
Cannot upgrade to 2.3 due to breaking changes (removal of  -g)

### ISSUE THREAD

**Issue by onovotny** [AArnott/Nerdbank.GitVersioning#275]
>So if your scenario requires both a NuGet-compatible semver v1 value for Chocolatey and a semver 2.0 version stamp on your actual NuGet package, NB.GV 2.3 is going to create problems for you unless we somehow fill that gap.

This is exactly my scenario as Chocolatey requires NuGet SemVer 1 compatible versions and gets tripped up by tags that start with a number. In my project, I build a nuget package and a chocolatey package and I'd like to use SemVer 2 for NuGet while having a "nuget semver 1" string available for chocolatey.

**Comment by AArnott** [comment]
I think I'll introduce a `ChocolateyPackageVersion` property version then. For now, it will be hard-coded to always be semver v1 (nuget subset). But if Chocolatey ever supports v2, we can either change it to v2, or add an option like we have for nuget.

**Comment by AArnott** [comment]
Will it be enough if this property is available via the `nbgv` CLI tool? Or do you need it as an msbuild property, or auto-stamped, or anything of that sort?

**Comment by AArnott** [comment]
Thanks for being an early adopter of v2.3 and reporting the issues.

**Comment by onovotny** [comment]
Thanks for the quick fix!
