### ISSUE TITLE
How to increment version with multiple features

### ISSUE THREAD

**Issue by NArnott** [AArnott/Nerdbank.GitVersioning#285]
Say I'm currently at version 2.1.*, and that I have 2 major features in the works on two different branches. To keep with semantic versioning, each major feature should result in a minor version update. So after these two features are complete, we should be at 2.3.0, and whichever feature is completed first would be at version 2.2.0

However, in practice, a dev on each branch would update the version json file up one minor version (from 2.1 to 2.2). And after both are checked in, we'd still be at 2.2, since the version is still based on the json file.

Are there any options for triggering a minor (or major) version update without adjusting the json file? Such as something in the commit comments?

**Comment by AArnott** [comment]
No, there's nothing automatic like that.

If releases are coming from master, generally the version bump happens within that branch. Assume that the developers working in the topic branches do not understand the release schedule or all the changes that are going into the next release. That would suggest the topic branches where features are developed aren't typically where the version bump should occur. Instead, topic branches just make feature changes, and merge into master.

Then the release manager(s) will bump version.json for master based on what they decide the impact is to customers. In your example, they would bump the minor version just once for one release, whether one or both features got in for that release. They'll then bump it again when another feature gets checked in that merits a minor version bump.
