### ISSUE TITLE
If an invalid version.json exists in the commit history it can break builds

### ISSUE THREAD

**Issue by dgriffen** [AArnott/Nerdbank.GitVersioning#286]
During a PR there was a mistake made in a `version.json` file that resulted in invalid json. The mistake looked like this:

```json
{
    "version": "16.0",
    "buildNumberOffset": 1000
    "assemblyVersion": "16.0"
}
```

Once the missing comma after 1000 was noticed a second commit was added to turn the file into this:

```json
{
    "version": "16.0",
    "buildNumberOffset": 1000,
    "assemblyVersion": "16.0"
}
```

The problem was that all builds after this point failed unless the two commits were squashed together so that no invalid version.json existed in the history.

**Comment by AArnott** [comment]
By design. See discussion in #251
