### ISSUE TITLE
optional ThisAssembly generation

### ISSUE THREAD

**Issue by japj** [AArnott/Nerdbank.GitVersioning#292]
Is it possible to (optionally) turn off the generation of the ThisAssembly class?

We had a situation where we hit an issue in combination with Fakes generation that took me a while to figure out. (this was eventually solved by adding `<Remove TypeName="ThisAssembly"/>` in the fakes config).

However, I am not sure if anyone has experienced issues where another library actually generates ThisAssembly content that would conflict with this library.
In that case they would also benefit from a 'switch'  to turn it off.

**Comment by AArnott** [comment]
I would accept a PR for this. Here's a mini-spec of how I would want it:

An msbuild property that turns it off. It should be called `GenerateThisAssemblyClass`, and passed into the `AssemblyVersionInfo` task. It should have a default value of `true`, set either in a (new) .props file or at the top of the .targets file, conditional on it not already having been set.

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.

**Comment by AArnott** [comment]
Oops. This actually *did* get fixed in #472

**Comment by AArnott** [comment]
Yes
