### ISSUE TITLE
Prepare-release command support for incrementing build variable

### ISSUE THREAD

**Issue by josesimoes** [AArnott/Nerdbank.GitVersioning#300]
I've used this new command a dozen times today to publish some releases and it's working great.
Great improvement that really speeds up this process!! 💯 

A questions: why shouldn't the versionIncrement field allow to use "build" and it's limited to major & minor? Sometimes one really wants to increment _just_ the build field.

**Comment by AArnott** [comment]
Thanks for the feedback. @ap0llo any particular reason you didn't implement support for incrementing the build variable?

**Comment by ap0llo** [comment]
I mainly omitted it because I didn't really see a use case, but I don't see why support for it couldn't be added.
The only aspect that could tricky is the naming of the release branch as this currently only cosiders major and minor version.

@josesimoes In your use case, would you expected to have release branches for two versions that only differ in the build number?

**Comment by ap0llo** [comment]
I'll look into it on the weekend

**Comment by josesimoes** [comment]
That's great!

Answering your question above, yes, sometimes we do have intermediate releases with quick fixes and such that only bump the build number.

**Comment by josesimoes** [comment]
Thinking about the release workflow it would be very helpfull if there was a switch in this command that allowed you to specify what to bump: major or minor.
The default would be what's in the config file but it does help to be able to specify that from the command line without having to manually change the file (which would kind of defeat the purpose of the command, right?)

Think of this: next time you are releasing a major version. You would have to edit version.jomson for either changing the version or the bump setting. 

Am I making sense?

**Comment by ap0llo** [comment]
Yes, makes sense. What you can do today is to override the automatically calculated next version wihtout changing version.json:

```
nbgv prepare-release --nextVersion X.Y
```

**Comment by josesimoes** [comment]
@ap0llo got you!

I just tried that and that is kind of messing with the version.json, but I guess that's expected.

starting point:
```
...
"1.1.0-preview.{height}",
...
```

command: `nbgv prepare-release --nextVersion 1.3` 

result:
```
...
"version": "1.3",
...
```

I have to use: `nbgv prepare-release --nextVersion 1.3.0-preview.{height}` in order to achieve the "expected" outcome (meaning: following the version pattern that was being used).

**Comment by AArnott** [comment]
I would have expected `-alpha` (or whatever the 'default' prerelease tag set in version.json is) to be added automatically, along with any subsequent prerelease tags in the original.

**Comment by ap0llo** [comment]
> I would have expected `-alpha` (or whatever the 'default' prerelease tag set in version.json is) to be added automatically, along with any subsequent prerelease tags in the original.

Currently, the value provided on the command line completely override the value from version.json. Looking at the above scenario, just allowing to override Major, Minor and Build would probably be sensible

**Comment by josesimoes** [comment]
Yes, if those switches become available, the pattern there should be respected and, on version bump, the parts bellow the set one would be zeroed. 

E.g.  on "minor" 1.3.22-preview.{height} would become 1.4.0-preview.{height}.

**Comment by ap0llo** [comment]
So support for incrementing the "build" portion of the version and adjusting the behavior of the command line options are two more-or-less independent features and I've decided to split it into multiple pull requests:

#301 Adds support for setting the version increment to `build`

I'll adjust the behaviour of the command line options in a later PR

**Comment by josesimoes** [comment]
Wondering if this is planned...

**Comment by AArnott** [comment]
Oh this appears to have been fixed a while back. All the PRs completed, but they didn't include the magic text in their comments to auto-close the issue. @josesimoes please let me know if you find the latest NB.GV version doesn't support this.
