### ISSUE TITLE
NPM package version should not use prerelease identifiers with leading zeros

### ISSUE THREAD

**Issue by fgreinacher** [AArnott/Nerdbank.GitVersioning#302]
```shell
> nbgv get-version
Version:                      0.1.32.9217
AssemblyVersion:              0.1.0.0
AssemblyInformationalVersion: 0.1.32+0124255961
NuGet package Version:        0.1.32-g0124255961
NPM package Version:          0.1.32-0124255961
```

In this case the build metadata of the NPM package version starts with a zero (`-012...`), which [is invalid per the semver spec](https://semver.org/#spec-item-9). This obviously happens sporadically based on which commit you're currently looking at.

---
My `version.json` is pretty much the default:

```json
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version": "0.1",
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^master$"
  ]
}
```

**Comment by AArnott** [comment]
Good catch.

**Comment by heaths** [comment]
Would it make sense to just prepend the "g" back in the prerelease metadata like for nupkgs?
