### ISSUE TITLE
Add $schema in generate version.json from nbgv install

### ISSUE THREAD

**Issue by psibernetic** [AArnott/Nerdbank.GitVersioning#312]
Including the schema in the default object would be handy to provide the intellisense to editors by default.

**Comment by AArnott** [comment]
I think we're already doing that:

https://github.com/AArnott/Nerdbank.GitVersioning/blob/01ebb81f18af1ce64659ad06267d86be96d1f8ad/src/nbgv/Program.cs#L214

What version of the `nbgv` global tool are you using when it doesn't work?

**Comment by psibernetic** [comment]
This was version 2.2.13

I had assumed dotnet tool install -g nbgv would update if newer version was available, bad assumption.

Confirmed this is working in 2.3.138.

Thanks!
