### ISSUE TITLE
Allow setting assembly version build number

### ISSUE THREAD

**Issue by dgriffen** [AArnott/Nerdbank.GitVersioning#313]
Currently the `assemblyVersion` property only allows `x.y` format. It should be expanded to allow `x.y.z` format.

**Comment by AArnott** [comment]
It also supports receiving a JSON *object* that allows setting it to match the build number that comes from the `version` property. Is that useful to you?

https://github.com/AArnott/Nerdbank.GitVersioning/blob/01ebb81f18af1ce64659ad06267d86be96d1f8ad/src/NerdBank.GitVersioning/version.schema.json#L45-L54
