### ISSUE TITLE
Add git commit timestamp to ThisAssembly

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/Nerdbank.GitVersioning#328]
It would be awesome if I could have some kind of timestamp information in my assembly. Using the build time is not a very good option, as the builds are no longer reproducible.

On the other hand, adding the timestamp of the git commit should just work fine - as rebuilding from the same commit would result in the same timestamp.

Is this something you'd consider? If you have some general idea on how to implement it, I'd be happy to try & write up a PR for this.

**Comment by AArnott** [comment]
Yes, I'd consider this as a PR. Since it seems rather unusual and likely to cause some confusion, I might want it conditional on an msbuild property.
