### ISSUE TITLE
Set version (tag = v{version}) only in one place 

### ISSUE THREAD

**Issue by lobster2012-user** [AArnott/Nerdbank.GitVersioning#331]
Hi!
~~I'm trying to use together [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning) and [SourceLink](https://github.com/dotnet/sourcelink) ([not supported tags now](https://github.com/dotnet/sourcelink/issues/224))
My vision of their perfect collaboration.~~
In one place I prescribe the version (prefix, suffix). For example in version.json
Then, if necessary, the tag is updated in the local repository(Automatically during build) ~~(and remote), then a built-in link is generated ((in nupkg and .pdb) ,(to the repository and sources)).~~

Can I do that now?

**Comment by AArnott** [comment]
I'm not sure what tags and versions have to do with SourceLink and PDBs. I use both SourceLink and NB.GV together all the time, but I don't think they intersect anywhere. SourceLink doesn't rely on tags -- it uses the git commit ID and remote URL.

**Comment by lobster2012-user** [comment]
Thanks for the answer.
Incorrectly formulated the question. I will still study the utility.
