### ISSUE TITLE
Add support for BuildingTag in VisualStudioTeamServices

### ISSUE THREAD

**Issue by haefele** [AArnott/Nerdbank.GitVersioning#332]
Hello,

after some investigation it seems like there might be some way to improve the VisualStudioTeamServices aka Azure DevOps integration.

Right now the `BuildingTag` is [not supported in Azure DevOps](https://github.com/AArnott/Nerdbank.GitVersioning/blob/63e0ff3130ed4e17225d6d56a21238cf4c81f2b6/src/NerdBank.GitVersioning/CloudBuildServices/VisualStudioTeamServices.cs#L18), but I think this can be improved and made to work.

I read [here](https://edsnider.net/2018/11/14/detecting-git-tag-pushes-in-azure-devops.html) that the `BUILD_SOURCEBRANCH` environment variable will start with `refs/tags/` when its building a tag.

So my idea is, when `BUILD_SOURCEBRANCH` starts with `refs/tags/` return a value from `BuildingTag` and return nothing from `BuildingBranch`.
Otherwise keep the existing behavior.

I'm just not sure in what kind format to return the value from `BuildingTag` - with or without the `refs/tags/` prefix?
In the AppVeyor integration, it seems to return only the tag name, without prefix.
But in the [version.json documentation](https://github.com/AArnott/Nerdbank.GitVersioning/blob/63e0ff3130ed4e17225d6d56a21238cf4c81f2b6/doc/versionJson.md) is a example with the prefix.

Any ideas or worries about this approach? 
Would gladly create a PR.

**Comment by AArnott** [comment]
Yes, I would accept a PR.
I suggest you follow the convention you see in the AppVeyor class, and test it with Azure DevOps to see if it works.

**Comment by haefele** [comment]
Alright, I'm gonna get to work on this then :smile:

Just as a small update, it seems like I got something mixed up, AppVeyor has the `refs/tags/` prefix (see [here](https://github.com/AArnott/Nerdbank.GitVersioning/blob/63e0ff3130ed4e17225d6d56a21238cf4c81f2b6/src/NerdBank.GitVersioning/CloudBuildServices/AppVeyor.cs#L31)).

Because of this confusion I decided to look through all of the supported cloud build services and see what they currently implement.

| Cloud Service | BuildingTag support| `refs/tags/` prefix |
|---|---|---|
|AppVeyor| ✔️ | ✔️  |
|GitLab| ✔️  | ❌  |
|Bamboo| ❌  | |
|Jenkins| ❌ | |
|TeamCity| ❌ | |
|Azure DevOps| ❌ | |
