### ISSUE TITLE
Tags and GitLab CI

### ISSUE THREAD

**Issue by grokys** [AArnott/Nerdbank.GitVersioning#335]
I want to build a public release when tagged using GitLab CI, and it seems that Nerdbank.GitVersioning is using the `CI_COMMIT_TAG` on GitLab.

Looking at the value of that variable on a tagged release, it is equal to the tag name without the `/refs/tags` prefix.

Should I be using `^v\\d+\\.\\d+` as my regex then on GitLab CI? Or is something not working as expected?

(Partially opening this issue just to help anyone who comes across the same problem)

**Comment by AArnott** [comment]
Thanks for reporting. This sounds like a minor bug in the gitlab extension, as it should normalize to add the refs/tags/ prefix.

https://github.com/AArnott/Nerdbank.GitVersioning/blob/c70a12a74638cc89aeb4500c581ab2ada944c47b/src/NerdBank.GitVersioning/CloudBuildServices/GitLab.cs#L22
