### ISSUE TITLE
Issue with .nuspec file

### ISSUE THREAD

**Issue by MarcoRossignoli** [AArnott/Nerdbank.GitVersioning#336]
We're setting up nighly build for Coverlet https://github.com/tonerdo/coverlet

We've 3 package to release, to do not waste space on MyGet we will publish only if we've new commit from previous "night".

We setup the things and works well for 2 of 3 package, one of our project uses nuspec file(with some files rules) and seem that when nuspec file is used git versioning doesn't work.

![image](https://user-images.githubusercontent.com/7894084/58367039-655bdc00-7eda-11e9-9d18-dc4d48dd2c27.png)

I'm a newbie with Nerdbank.GitVersioning, so likely I missing something

Here the draft PR https://github.com/tonerdo/coverlet/pull/423/files
Here csproj and nugetspec https://github.com/tonerdo/coverlet/tree/master/src/coverlet.collector

Can someone help me?

cc: @AArnott @onovotny @tonerdo

**Comment by onovotny** [comment]
I replied in the thread.

**Comment by MarcoRossignoli** [comment]
Great thank's Oren!

**Comment by AArnott** [comment]
I've commented there too. Let's continue the conversation there.
