### ISSUE TITLE
New template of Version.new breaking nanoFramework build

### ISSUE THREAD

**Issue by josesimoes** [AArnott/Nerdbank.GitVersioning#346]
Hi,

We at [nanoFramework](https://github.com/nanoframework) are using Nerdbank.GitVersioning in our class libs. It uses it's project system and mscorlib.
Starting with v3.0.13-beta the builds start failing because of a change in the version.new file:

```
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.6.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.6")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.6-preview.3+192e6bb6bf")]
[System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.0.15.60440")]
internal static partial class ThisAssembly {
    internal const string AssemblyVersion = "1.0.6.0";
    internal const string AssemblyFileVersion = "1.0.6";
    internal const string AssemblyInformationalVersion = "1.0.6-preview.3+192e6bb6bf";
    internal const string AssemblyName = "System.Net.Http";
    internal const string AssemblyConfiguration = "Debug";
    internal const string GitCommitId = "192e6bb6bf0549deb83888e4654d24bdca5733e9";
    internal const string PublicKey = "00240000048000009400000006020000002400005253413100040000010001001120aa3e809b3da4f65e1b1f65c0a3a1bf6335c39860ca41acb3c48de278c6b63c5df38239ec1f2e32d58cb897c8c174a5f8e78a9c0b6087d3aef373d7d0f3d9be67700fc2a5a38de1fb71b5b6f6046d841ff35abee2e0b0840a6291a312be184eb311baff5fef0ff6895b9a5f2253aed32fb06b819134f6bb9d531488a87ea2";
    internal const string PublicKeyToken = "c07d481e9758c731";
    internal static readonly System.DateTimeOffset GitCommitDate = new System.DateTimeOffset(636949220730000000, System.TimeSpan.Zero);
    internal const string RootNamespace = "System.Net.Http";
}
```
the build exception is:

```
  obj\Release\System.Net.Http.Version.cs(14,9): error CS0234: The type or namespace name 'CodeDom' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\a\1\s\source\nanoFramework.System.Net.Http\System.Net.Http.nfproj]
  obj\Release\System.Net.Http.Version.cs(24,37): error CS0234: The type or namespace name 'DateTimeOffset' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\a\1\s\source\nanoFramework.System.Net.Http\System.Net.Http.nfproj]
```

That's because we don't have 'CodeDom' nor 'DateTimeOffset'.
Not sure how impacting this is but any chance couldn't could review if these are really necessary or suggest a workaround it? Thanks!

**Comment by AArnott** [comment]
Thanks for the report, and I'm glad you're trying out the v3.0 beta!

I don't know anything about the nano framework. Is the idea that you have a subset of .NET types that doesn't include `DateTimeOffset`? The [apisof.net](https://apisof.net/catalog/System.DateTimeOffset) report on that type is that basically everyone supports it, since .NET 2.0. But nanoframework isn't represented on that site.
Anyway, we could change `DateTimeOffset` to `DateTime`. I'm guessing you have *that* type in nanoframework, right?

Regarding CodeDom, I wasn't aware we had introduced that attribute recently. No reason to keep it though AFAIK, so we can remove it.

**Comment by ap0llo** [comment]
Alternatively, the incompatible attributes/members could be left out when generating code for this framework. Perhaps a MSBuild property to switch it off or using `#ifdef`

**Comment by josesimoes** [comment]
Always on the edge! 🙂
In a nutshell: .NET nanoFramework allows writing C# apps for small, resource constrained micro-controllers. It picked up where .NETMF left.

Because of those constrains our mscorlib has only a subset of the “full” frameworks. DateTimeOffset is one that's not there…

Thanks for considering removing the CodeDom attribute!


________________________________
De: Andrew Arnott <notifications@github.com>
Enviado: Friday, May 31, 2019 8:56:21 PM
Para: AArnott/Nerdbank.GitVersioning
Cc: José Simões; Author
Assunto: Re: [AArnott/Nerdbank.GitVersioning] New template of Version.new breaking nanoFramework build (#346)


Thanks for the report, and I'm glad you're trying out the v3.0 beta!

I don't know anything about the nano framework. Is the idea that you have a subset of .NET types that doesn't include DateTimeOffset? The apisof.net<https://apisof.net/catalog/System.DateTimeOffset> report on that type is that basically everyone supports it, since .NET 2.0. But nanoframework isn't represented on that site.
Anyway, we could change DateTimeOffset to DateTime. I'm guessing you have that type in nanoframework, right?

Regarding CodeDom, I wasn't aware we had introduced that attribute recently. No reason to keep it though AFAIK, so we can remove it.

**Comment by josesimoes** [comment]
That could work too.

________________________________
De: Andreas Grünwald <notifications@github.com>
Enviado: Saturday, June 1, 2019 11:15:09 AM
Para: AArnott/Nerdbank.GitVersioning
Cc: José Simões; Author
Assunto: Re: [AArnott/Nerdbank.GitVersioning] New template of Version.new breaking nanoFramework build (#346)


Alternatively, the incompatible attributes/members could be left out when generating code for this framework. Perhaps a MSBuild property to switch it off or using #ifdef

**Comment by AArnott** [comment]
I don't think CodeDOM lets us emit `#if`.
What msbuild properties or preprocessor define symbols are unique to targeting NanoFramework?

**Comment by josesimoes** [comment]
Please take a look at [this](https://github.com/nanoframework/nf-Visual-Studio-extension/blob/b44145837a05b5ce9b6e335f02db6d9d3e525bb7/source/VisualStudio.Extension/Targets/NFProjectSystem.CSharp.targets#L4) PropertyGroup on one of the targets file of our project system.

Define symbol `NANOFRAMEWORK_V1_0` is an option along with any of the `TargetFramework(...)` msbuild properties.

**Comment by AArnott** [comment]
Thanks.
FWIW the pattern for define symbols for all other framework types would suggest you define `NANOFRAMEWORK`, `NANOFRAMEWORK_1_0` (no `V`).

**Comment by josesimoes** [comment]
Nice catch! Thanks. 🙂
I'll fix that for coherence. Consider it without the V.

________________________________
De: Andrew Arnott <notifications@github.com>
Enviado: Sunday, June 2, 2019 2:46:36 PM
Para: AArnott/Nerdbank.GitVersioning
Cc: José Simões; Author
Assunto: Re: [AArnott/Nerdbank.GitVersioning] New template of Version.new breaking nanoFramework build (#346)


Thanks.
FWIW the pattern for define symbols for all other framework types would suggest you define NANOFRAMEWORK, NANOFRAMEWORK_1_0 (no V).

**Comment by AArnott** [comment]
Since I suppose you aren't defining `NETSTANDARD` or `NETFRAMEWORK`, I might check for those instead of checking for NANOFRAMEWORK explicitly. Not sure yet.
But honestly I might just drop the attribute and change to `DateTime` to avoid the conditional compilation.

**Comment by josesimoes** [comment]
Got you! Whatever works best for you.

I really appreciate you are looking into this and accommodate the changes to make this work with nanoFramework. 👍🙂


________________________________
De: Andrew Arnott <notifications@github.com>
Enviado: Sunday, June 2, 2019 6:48:36 PM
Para: AArnott/Nerdbank.GitVersioning
Cc: José Simões; Author
Assunto: Re: [AArnott/Nerdbank.GitVersioning] New template of Version.new breaking nanoFramework build (#346)


Since I suppose you aren't defining NETSTANDARD or NETFRAMEWORK, I might check for those instead of checking for NANOFRAMEWORK explicitly. Not sure yet.
But honestly I might just drop the attribute and change to DateTime to avoid the conditional compilation.

**Comment by r-bennett** [comment]
We're also seeing the same issue with SQL Server database projects (`.sqlproj`)

**Comment by AArnott** [comment]
Is all this unique to 3.0 or are you seeing this on earlier versions?

**Comment by r-bennett** [comment]
I'm seeing this on 2.3.138

**Comment by r-bennett** [comment]
Turns out the .sqlproj problem was only an issue with net452 - updgrading to net461 brings in the required `CodeDom` reference
