### ISSUE TITLE
[Question]nbgv get-commits

### ISSUE THREAD

**Issue by MarcoRossignoli** [AArnott/Nerdbank.GitVersioning#348]
I'm testing usage of `nbgv get-commits` commands on coverlet repo https://github.com/tonerdo/coverlet/commits/master

I would like to know if it's expected that if I ask for last version done by only 1 commit it returns "no results"
```
D:\git\coverlet\src\coverlet.collector (master -> origin)
λ nbgv get-commits 1.0.25

D:\git\coverlet\src\coverlet.collector (master -> origin)
λ nbgv get-commits 1.0.24
e5998d8fbd07376dd8908e4829dda208d82d582d 1.0.24.39397 Merge pull request #451 from AArnott/versionPatch
```
I would expect `6209239d697b3e2fbd0ddfbe4e3d6e7e6cc6c212` from 1.0.25
Nightly for reference https://www.myget.org/feed/coverlet-dev/package/nuget/coverlet.collector/1.0.25-g6209239d69

I would like prepare a doc with "nightly usage" infos and the idea is document how get commit hash from version.

cc: @AArnott @tonerdo

**Comment by MarcoRossignoli** [comment]
Never mind my fault...I was not synched with master.

**Comment by AArnott** [comment]
You'll need to be using the 3.0-beta for your repo.
And FYI, I found a bug in this area in the 3.0 version that I've yet to fix.

**Comment by AArnott** [comment]
#347 is the issue I found.

**Comment by MarcoRossignoli** [comment]
I'm using 
```
nbgv                                   2.3.167                     nbgv
```
and it works 
```
D:\git\coverlet\src\coverlet.collector (master -> origin)
λ nbgv get-commits 1.0.25
6209239d697b3e2fbd0ddfbe4e3d6e7e6cc6c212 1.0.25.2402 Merge pull request #441 from AArnott/fixPackageOutputPath
```
