### ISSUE TITLE
Make nbgv get-version -v friendlier

### ISSUE THREAD

**Issue by asherber** [AArnott/Nerdbank.GitVersioning#366]
Running `nbgv get-version` gives output like this:

```
λ nbgv get-version
Version:                      0.0.17.64061
AssemblyVersion:              0.0.0.0
AssemblyInformationalVersion: 0.0.17+3dfad7e587
NuGet package Version:        0.0.17-g3dfad7e587
NPM package Version:          0.0.17-g3dfad7e587
```
The first three of these variable names can be passed as-is to `nbgv get-version -v`, but the last two need to be `NuGetPackageVersion` and `NpmPackageVersion`, which is not apparent.

I would suggest changing the last two printed variable names to match the strings that `nbgv get-version -v` expects. I would also suggest changing the behavior of this command to be case-insensitive with regard to variable names.

I'm happy to put together a PR if this is acceptable.

**Comment by AArnott** [comment]
Sounds great. Thanks for volunteering.
