### ISSUE TITLE
Enable custom .net core dotnet process calls in getVersion and setPackageVersion

### ISSUE THREAD

**Issue by magriff** [AArnott/Nerdbank.GitVersioning#379]
I would like to onboard this package as part of a versioning solution for our components that build using gulp. Unfortunately our internal build servers do not allow direct calls to "dotnet" alias as it's not setup on the build servers and they contain multiple versions of the .net core dotnet cli process. 

In the index.ts file there is a getVersion() method that calls execAsync() method. This method calls "dotnet" directly. I would like to propose that this method be modified as such to allow callers to pass in a location where dotnet process resides:

    /**
     * Gets an object describing various aspects of the version of a project.
     * @param projectDirectory The directory of the source code to get the version of.
     * @param dotnetCommand The location of the dotnet command line executable
     */
    export async function getVersion(projectDirectory?: string, dotnetCommand?: string): Promise<IGitVersion> {
        projectDirectory = projectDirectory || '.';
        var command = dotnetCommand || 'dotnet';
        var getVersionScriptPath = path.join(__dirname, nbgvPath, "tools", "netcoreapp2.1", "any", "nbgv.dll");
        var versionText = await execAsync(`${command} "${getVersionScriptPath}" get-version --format json`, { cwd: projectDirectory })
        if (versionText.stderr) {
            throw versionText.stderr;
        }

        var directResult = JSON.parse(versionText.stdout);
        var result = {};
        for (var field in directResult) {
            result[camelCase(field)] = directResult[field];
        }

        return <IGitVersion>result;
    }

In addition to the above I would propose a change to setPackageVersion() method to include a dotnetCommand parameter as well that contains the location to the dotnet process:

    /**
     * Sets an NPM package version based on the git height and version.json.
     * @param packageDirectory The directory of the package about to be published.
     * @param srcDirectory The directory of the source code behind the package, if different than the packageDirectory.
     * @param dotnetCommand The location of the dotnet command line executable
     */
    export async function setPackageVersion(packageDirectory?: string, srcDirectory?: string, dotnetCommand?: string) {
        packageDirectory = packageDirectory || '.';
        srcDirectory = srcDirectory || packageDirectory;
        const gitVersion = await getVersion(srcDirectory, dotnetCommand);
        console.log(`Setting package version to ${gitVersion.npmPackageVersion}`);
        var result = await execAsync(`npm version ${gitVersion.npmPackageVersion} --no-git-tag-version`, { cwd: packageDirectory });
        if (result.stderr) {
            console.log(result.stderr);
        }
    }

Thanks in advance for your consideration.

**Comment by AArnott** [comment]
Sounds good. Send a PR?

**Comment by magriff** [comment]
I cannot push changes to a remote branch in order to send a PR. I don't appear to have access. My GitHub username is magriff@microsoft.com

remote: Permission to AArnott/Nerdbank.GitVersioning.git denied to magriff.
fatal: unable to access 'https://github.com/AArnott/Nerdbank.GitVersioning.git/': The requested URL returned error: 403

**Comment by AArnott** [comment]
@magriff That's to be expected. You need to fork the repo on github first, push to your fork, then create a PR from there. That's standard github process.

**Comment by magriff** [comment]
I see. First time contributing for me on GitHub. I have created a PR: https://github.com/AArnott/Nerdbank.GitVersioning/pull/380

**Comment by magriff** [comment]
@AArnott I sent out a PR. Do you plan to commit the PR (https://github.com/AArnott/Nerdbank.GitVersioning/pull/380)? I have tested out this change in our build environment and it's working as expected.

**Comment by AArnott** [comment]
Thanks for the reminder. I lost track of it, but will review it in the next day or two.

**Comment by AArnott** [comment]
Ha! It turns out it really was simple. So sorry it took me so long to review it. The release to nuget.org is in progress. Watch for 3.1.12-beta.

**Comment by AArnott** [comment]
oh... and released to npmjs.org as well, of course.
