### ISSUE TITLE
Getting "Detached head" error in Azure Pipeline build

### ISSUE THREAD

**Issue by josesimoes** [AArnott/Nerdbank.GitVersioning#383]
Hi,

I was trying to improve our Azure Pipeline yaml to handle the preparation to a new release right on the build.
For that I added this on a PS step:
`nbgv prepare-release`

Upon execution it fails with this:
`Detached head. Check out a branch first.` 

I've cloned the repo locally and tried that on a PowerShell console without any issues and getting the expected outcome: a new branch and the current version config bumped.

Any ideas on what am I missing here?

Thanks!

**Comment by ap0llo** [comment]
I think Azure Pipelines doesn't really check out the branch for the build and rather just checks out the commit directly. So git (and nbgv for that matter) doesn't really known which branch you are currently on.

Running a explicit `git checkout <Branch>` could make it work.

**Comment by josesimoes** [comment]
@ap0llo you correct!
I've tried to do that git checkout without success. For some reason, it doesn't like to "checkout" on a detached head...

I ended up cloning the repo to the Pipeline temp folder and call nbgv on that one to do the prepare-release. All this is in PowerShell script.

Something curious that I couldn't find a way through: I'm not able to pass parameters to the tool using an Azure Pipeline variable.
My idea was to have a pipeline var, like NbgvParameters. With the default being an empty string.
The call to the tool in the PS1 is (was):
`nbgv prepare-release $env:NbgvParameters` 

Couldn't make is work because nbgv always complained about the parameters with:
`error: invalid option --versionIncrement build`

I tried several variations: with double quotes on the full line, double quotes just on the variable, single quotes. Nothing seemed to work...

If this is of interest to anyone the Azure Pipeline is [here](https://dev.azure.com/nanoframework/nanoFramework.Networking.Sntp/_build?definitionId=1&_a=summary). Look for the failed jobs from yesterday and specifically the "NBGV prepare release" step.

Thanks anyway! 😃

**Comment by AArnott** [comment]
I think your failure is because ps1 considers the entire env var to be a single argument instead a string of space delimited arguments. Powershell has a syntax or two to support what you're trying to do but I can't remember them off-hand.

**Comment by josesimoes** [comment]
@AArnott got you! Thanks for the hint.
I've search around that but could find any alternative that worked…
Will give it another try.

**Comment by dariusonsched** [comment]
> I ended up cloning the repo to the Pipeline temp folder and call nbgv on that one to do the prepare-release. All this is in PowerShell script.
> 
> If this is of interest to anyone the Azure Pipeline is [here](https://dev.azure.com/nanoframework/nanoFramework.Networking.Sntp/_build?definitionId=1&_a=summary). Look for the failed jobs from yesterday and specifically the "NBGV prepare release" step.

@josesimoes it would be super helpful to me and to the audience if you shared the actual script.  I am struggling to get `nbgv prepare-release` working in the same situation.

If you would kindly share that script along with any supporting steps - e.g. saw a `Set Git Identity` step in your pipeline.
