### ISSUE TITLE
A commit from the future breaks nbgv cloud variables

### ISSUE THREAD

**Issue by sonofhammer** [AArnott/Nerdbank.GitVersioning#384]
`nbgv get-version` and `nbgv  cloud` return different git heights when commit history contains a commit from the future.

To reproduce:
1. install v3.0.25 of nbgv ( `dotnet install nbgv -g --version 3.0.25` )
2. Clone [this repo]( https://github.com/sonofhammer/GitVersioningBugRepro)
3. run `nbgv get-version` observe the following output
```
Version:                      1.0.4.35936
AssemblyVersion:              1.0.0.0
AssemblyInformationalVersion: 1.0.4-beta+608c06f12c
NuGetPackageVersion:          1.0.4-beta
NpmPackageVersion:            1.0.4-beta
```
4. Run `nbgv cloud -s VisualStudioTeamServices` observe the following output
```
##vso[build.updatebuildnumber]1.0.3-beta
```

5. observe how `cloud` param will shows `3` for git height, whereas `get-version` shows 4.

6. make a new commit to the local repo, rerun `get-version` and `cloud` commands again. observe how the numbers go up for the first, but not the second.

Possible root cause: It appears that `nbgv get-version` gets git height for current head, whereas `nbgv cloud` gets git height for the commit in the repository with the newest date

**Comment by AArnott** [comment]
That's _very_ interesting. the `cloud` command should certainly not just go for the newest date commit. Thanks for the repro repo. 

I'll take a look.

**Comment by AArnott** [comment]
Yup, you're absolutely right: the `cloud` command takes a path that is meant to use HEAD but we use a means to get the commit at HEAD that simply takes the one with the latest date. Gah!

**Comment by sonofhammer** [comment]
Thank you for the quick response on this :)

**Comment by AArnott** [comment]
You're welcome. Look for 3.0.26 on nuget.org to get the fix.

Your repo and analysis certainly helped get this out quickly.
