### ISSUE TITLE
Multiple version.json

### ISSUE THREAD

**Issue by Masterwow3** [AArnott/Nerdbank.GitVersioning#387]
Hi,

we currently have the scenario, a product which is created with different version numbers.
The problem: With ngbv we can only create one version.json.
How would you suggest to solve the problem?
Would it make sense to support multiple version.json, e.g. buildA-version.json and buildB-version.json.

**Comment by AArnott** [comment]
I don't understand why you say only one version.json is supported. nbgv absolutely supports multiple version.json files. They have to be in different directories. The typical setup is that you put one in the root of your repo, but can override it with different settings or version numbers by dropping it in other directories next to the project files that need something different.

**Comment by samtrion** [comment]
How does the whole thing behave when you call `prepare-release`?

Which version number is used for the release branch?
Is there a way to just tag instead of a release branch?

**Comment by Masterwow3** [comment]
@AArnott sorry for the late answer, we will do this the way you described it. We wondered if there was another way. Thank you very much for the answer.

**Comment by AArnott** [comment]
@samtrion Please open a distinct issue for your question(s).
