### ISSUE TITLE
Wrong version produced when changing version.json

### ISSUE THREAD

**Issue by shana** [AArnott/Nerdbank.GitVersioning#389]
Hey hey! First off, love the project, it's solving almost all my versioning issues! I hit a thing that might or might not be a bug (or maybe I'm missing something, dunno)...

I have about 10 projects in a repo, and I'm following the instructions at https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md#set-them-from-just-one-project to set the cloud build variables from only one project. I have a version.json in the root like this:

**version.json at root:**
```
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "version":  "1.0",
  "publicReleaseRefSpec": [
    "^refs/heads/master$",
    "^refs/heads/v\\d+(?:.\\d+)?$"
  ],
  "cloudBuild": {
    "setVersionVariables": false,
    "buildNumber": {
      "enabled": false
    }
  },  
  "inherit": false
}
```

**version.json in all project subdirectories except MasterProject:**
```
{
    "$schema":  "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
    "inherit":  true
}
```

**version.json in MasterProject:**
```
{
  "$schema": "https://raw.githubusercontent.com/AArnott/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",
  "cloudBuild": {
    "setVersionVariables": true,
    "buildNumber": {
      "enabled": true
    }
  },
  "inherit": true
}
```

It all works great except that I moved the projects down one subdirectory. The root version.json file has not been changed. After this move, all theprojects have their versions bumped correctly in a local build (from `1.0.9` to `1.0.10`) EXCEPT for the MasterProject, which misteriously got stamped with `1.0.0`. If I take out the the `cloudBuild` section in the MasterProject, it gets versioned correctly. Looks like it thinks that the version.json file in the MasterProject has changes that affect the version?

**Comment by shana** [comment]
Ah, cool, I'll try that, thanks!

**Comment by AArnott** [comment]
So your root version.json is and always has been in the repo root, right? 

Can you share the repo or whip up a repro repo that you can share?

**Comment by shana** [comment]
@AArnott Yeah, the version.json in the root was never touched. The repo is https://github.com/spoiledcat/UnityTools, but I've moved some other things around and suddenly it's versioning things correctly, I can't reproduce it anymore. I have no idea what was happening or why it stopped happening :-/

**Comment by AArnott** [comment]
Well, that's good---ish.  ;-p

One thing that frequently trips up people is that changes to version.json must be *committed* for everything to apply properly. Maybe when you were seeing the unexpected behavior, you only had local changes that hadn't been committed yet.

**Comment by shana** [comment]
Maybe, could have been that. If it happens again, I'll try to isolate it. Thanks!
