### ISSUE TITLE
Referencing variables in YAML

### ISSUE THREAD

**Issue by rioka** [AArnott/Nerdbank.GitVersioning#397]
_Just started working with VSTS, so maybe it's a trivial question_

I'm trying to use variables in a vsts yaml script.
I can reference, e.g. `$(GitAssemblyInformationalVersion)`, and use to build up filenames, but if I try to use it e.g. as part of a task's `displayName`, it is not replaced, i.e. the output for 
```
  displayName: 'Publishing v$(GitAssemblyInformationalVersion)'
```
is 
`Publishing v$(GitAssemblyInformationalVersion)`

However, I can reference, e.g. `$(BuildConfiguration)` in a similar way in `displayName`, and get expected result

Is that standard behavior?

**Comment by AArnott** [comment]
I believe it only works if the variable is set before the task first appears on the web page. BuildConfiguration works because it's set in advance.

**Comment by rioka** [comment]
👍 thx
