### ISSUE TITLE
WPF: Build fails in wpftmp.csproj when `ThisAssembly` is used

### ISSUE THREAD

**Issue by hypervtechnics** [AArnott/Nerdbank.GitVersioning#404]
I am trying to embed the library within a WPF app targeting netcoreapp3.0.

### Repro

1. Create WPF (.NET Core) via Visual Studio 2019.
2. Create Git repository via Git UI in VS.
3. Install `NerdBank.GitVersioning` via NuGet UI.
4. Add `Title = ThisAssembly.GitCommitId;` to the MainWindow constructor.
5. Try to build the application.

The IntelliSense suggests ThisAssembly and also shows the right constant values in the tooltip (the class is generated somewhere), but when it comes the build:

```
1>------ Build started: Project: VersioningTest, Configuration: Debug Any CPU ------
1>MainWindow.xaml.cs(13,21,13,33): error CS0103: The name 'ThisAssembly' does not exist in the current context
1>Done building project "VersioningTest_deh445kx_wpftmp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### What I tried then

1. If you remove the line added in 3 the app successfully builds & runs. When you add the line `Title = typeof(MainWindow).Assembly.GetName().Version.ToString();` instead the version is `0.0.0.0`.
2. During installation no version.json was created. I added one on project level and as this did not work in the git root which didn't work either. 
3. I executed `nbgv install` via packet manager console on solution(= git repo root) level, after installing it as a global tool. Still did not work. On project level did not work either (created files at same location).
4. Used `Title = typeof(MainWindow).Assembly.GetName().Version.ToString();` and `nbgv install`. Version displayed is `1.0.0.0`.

### Context

My project file:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

I did not find any issues related to this issue.

**Comment by AArnott** [comment]
The issue with WPF is it has this horky "inner build" which builds a temporary project file that doesn't properly import the nuget imported files. This is tracked by https://github.com/NuGet/Home/issues/5894.

As for version numbers being 0.0.0.0, that may be because you didn't *commit* your version.json file. Did you try that?

**Comment by hypervtechnics** [comment]
> you didn't _commit_ your version.json file

Yeah. I forgot that. 🤦‍♂

**Comment by AArnott** [comment]
The best I can do given current NuGet/WPF bugs is now released in nerdbank.gitversioning v3.0.28. Upgrade to that and apply the following workaround:

Add this just under the opening `<Project>` tag:

```xml
  <Import Project="$(BaseIntermediateOutputPath)$(_TargetAssemblyProjectName)$(MSBuildProjectExtension).nuget.g.props"
          Condition=" '$(_TargetAssemblyProjectName)' != '' and '$(ImportProjectExtensionProps)' != 'false' and exists('$(BaseIntermediateOutputPath)$(_TargetAssemblyProjectName)$(MSBuildProjectExtension).nuget.g.props')" />
```

Add this just above the closing `</Project>` tag:

```xml
  <Import Project="$(BaseIntermediateOutputPath)$(_TargetAssemblyProjectName)$(MSBuildProjectExtension).nuget.g.targets"
          Condition=" '$(_TargetAssemblyProjectName)' != '' and '$(ImportProjectExtensionProps)' != 'false' and exists('$(BaseIntermediateOutputPath)$(_TargetAssemblyProjectName)$(MSBuildProjectExtension).nuget.g.targets')" />
```

This is tested to work both for .NET Framework WPF projects and .NET Core WPF projects.

**Comment by hypervtechnics** [comment]
Now it is working. Thank you for the quick workaround 😄 !

**Comment by wjk** [comment]
@AArnott Unfortunately, this issue is happening with [one of my projects](https://github.com/wjk/MSIExtractApp/tree/ThisAssembly), and the workaround you proposed in https://github.com/dotnet/Nerdbank.GitVersioning/issues/404#issuecomment-554416254 isn’t working for me. Could you please reopen this issue so we can look into this? I’m using NBGV 3.1.74, which is larger than the version that you specified (3.0.28). Thanks!

**Comment by wjk** [comment]
Please disregard my earlier comment; I have since [fixed the issue](https://github.com/wjk/MSIExtractApp/commit/a9a414f0e154b03f1daedeca2f5487ec7ee24135). Sorry to bother you!

**Comment by inthemedium** [comment]
To aid others, I found another instance where the workaround above fixes the issue below. You can get in this situation with usage of `InternalsVisibleTo` in dependencies of a WPF project.

`SomeFileUnderAWpfProject.cs(42,42): error CS0433: The type 'ThisAssembly' exists in both 'AssemblyA, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'AssemblyB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [wpfproject_x3jmmw55_wpftmp.csproj]`

**Comment by AArnott** [comment]
It is also worth noting that the WPF team finally fixed this bug, although you need a recent SDK to get the fix. Details are here: https://github.com/microsoft/CsWin32/issues/7

**Comment by lordscarlet** [comment]
I am having this problem on a project that is not WPF (`<Project Sdk="Microsoft.NET.Sdk">`), but is net standard (`<TargetFrameworks>net7.0;net48;</TargetFrameworks>`). I don't know if that may be relevant. I have tried to scour through all of the relevant issues here and tried the workarounds, but no solution yet.

**Comment by lordscarlet** [comment]
@AArnott ok, I am back. I am trying to apply this to an ASP.NET full framework application. I can build locally, but in the pipeline on ADO I still get the error above. I was able to solve it locally by adding the `Directory.build.targets` mentioned above, but that doesn't seem to help it when it gets to the build server.

**Comment by AArnott** [comment]
What OS is your build server running? `Directory.Build.targets` is the proper capitalization, so if the build server is non-Windows, it wouldn't work with your `Directory.build.targets` file.
I know you said 'full framework', but there's mono, so... just considering possibilities here.
