### ISSUE TITLE
How to use calculated version(s) to pre-process files in the build?

### ISSUE THREAD

**Issue by Eilon** [AArnott/Nerdbank.GitVersioning#406]
In my scenario I have a repo that contains some projects that represent NuGet packages with DLLs, plus some .NET CLI template packages that have projects that need to reference the build NuGet packages. Because the NuGet package versions are generated dynamically (thanks, NerdBank! 😄), I figured I need to use `$(NuGetPackageVersion)` to process my template files and get that version injected into them.

I figure one strategy is to have a file such as `templates\.template.config\template.json.in` (note the `.in` extension) that has text `REPLACE_VERSION` in it, then with an MSBuild target that runs at a suitable time, replace `REPLACE_VERSION` with `$(NuGetPackageVersion)` and save the file as `templates\.template.config\template.json`, and let the build continue with the substituted values.

Does anyone know any guidance or sample of how to do this?

**Comment by AArnott** [comment]
Yes, I've done this in a few places, including an OSS repo very recently:

https://github.com/microsoft/vs-threading/pull/554/files#diff-81f1e2b7e2669d47bc2274efe06588f9

**Comment by Eilon** [comment]
Awesome, I was able to use something very close to that and get my stuff working.

Because I'm running w/ .NET Core, I wasn't able to use `CodeTaskFactory`, but had to use `RoslynCodeTaskFactory` instead, with slightly tweaked imports:

```xml
  <UsingTask TaskName="ReplaceFileText" TaskFactory="RoslynCodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <ParameterGroup>
      <InputFilename ParameterType="System.String" Required="true" />
      <OutputFilename ParameterType="System.String" Required="true" />
      <MatchExpression ParameterType="System.String" Required="true" />
      <ReplacementText ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Using Namespace="System" />
      <Using Namespace="System.IO" />
      <Using Namespace="System.Text.RegularExpressions" />
      <Code Type="Fragment" Language="cs">
        <![CDATA[
            File.WriteAllText(
                OutputFilename,
                Regex.Replace(File.ReadAllText(InputFilename), MatchExpression, ReplacementText)
                );
          ]]>
      </Code>
    </Task>
  </UsingTask>
```

**Comment by AArnott** [comment]
> Because I'm running w/ .NET Core, I wasn't able to use CodeTaskFactory, but had to use RoslynCodeTaskFactory instead

How very peculiar. I use my version in a few different repos that all work with `dotnet build`. I wonder what went wrong for your case.

**Comment by paulomorgado** [comment]
When I want to see what happened in MSBuild: http://www.msbuildlog.com/

**Comment by Eilon** [comment]
I got an error saying that CodeTaskFactory wasn't supported, then Bing led me to RoslynCodeTaskFactory. I'd have to try again to see what the error was.

**Comment by Eilon** [comment]
This post is old but it seemed to match what I saw (I think): https://github.com/Microsoft/msbuild/issues/2890

I'm running .NET Core 3.0 and 3.1, but I'm not sure which I was using when I got the error.
