### ISSUE TITLE
What happened to Get-CommitId

### ISSUE THREAD

**Issue by devhawk** [AArnott/Nerdbank.GitVersioning#410]
tools directory appears to have disappeared. Am I missing something?

**Comment by AArnott** [comment]
It's still there in the nupkg file. Where are you looking for it?

But ya, you may have missed something: the script is deprecated in favor of [the `nbgv` dotnet CLI tool](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/doc/nbgv-cli.md).

**Comment by devhawk** [comment]
I was looking in the repo for the scripts. Didn't realize that functionality is now in the CLI tool. You should probably update readme.md as it still references the scripts in the tools directory

BTW, I'm a huge fan of this tool! Thanks so much for creating it @AArnott!

**Comment by AArnott** [comment]
Well, the [scripts are still in the repo](https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/Nerdbank.GitVersioning.Tasks/tools/Get-CommitId.ps1).

Thanks for reminding me to update the readme file.
