### ISSUE TITLE
GetBuildVersion task doesn't load

### ISSUE THREAD

**Issue by devhawk** [AArnott/Nerdbank.GitVersioning#413]
I can build [this commit](https://github.com/neo-project/neo-fx/tree/devhawk/gitversion-test) of my project without issue. If I update the global.json file to use dotnet core sdk 3.1.100, I get the following build error:

> C:\Users\harry\.nuget\packages\nerdbank.gitversioning\3.0.26\build\Nerdbank.GitVersioning.targets(63,5): error MSB4062: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task could not be loaded from the assembly C:\Users\harry\.nuget\packages\nerdbank.gitversioning\3.0.26\build\MSBuildCore/Nerdbank.GitVersioning.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\harry\Source\neo\seattle\fx\tests\NeoFxTests\NeoFxTests.csproj]

I noticed there is an update to Nerdbank.GitVersioning (v3.0.26 -> v3.0.28) so I tried updating that, but I still get the error. If I revert global.json back to using SDK 3.0.100 but leave GitVersioning on v3.0.28, I get the error as well (twice):

> C:\Users\harry\.nuget\packages\nerdbank.gitversioning\3.0.28\build\Nerdbank.GitVersioning.targets(71,5): error MSB4062: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task could not be loaded from the assembly C:\Users\harry\.nuget\packages\nerdbank.gitversioning\3.0.28\build\MSBuildCore/Nerdbank.GitVersioning.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\harry\Source\neo\seattle\fx\src\RocksDb\NeoFx.RocksDb.csproj]
C:\Users\harry\.nuget\packages\nerdbank.gitversioning\3.0.28\build\Nerdbank.GitVersioning.targets(71,5): error MSB4062: The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task could not be loaded from the assembly > C:\Users\harry\.nuget\packages\nerdbank.gitversioning\3.0.28\build\MSBuildCore/Nerdbank.GitVersioning.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\harry\Source\neo\seattle\fx\tests\NeoFxTests\NeoFxTests.csproj]

SDKs Installed (via dotnet --list-sdks): 
- 2.1.802 [C:\Program Files\dotnet\sdk]
- 2.2.402 [C:\Program Files\dotnet\sdk]
- 3.0.101 [C:\Program Files\dotnet\sdk]
- 3.1.100 [C:\Program Files\dotnet\sdk]

**Comment by devhawk** [comment]
This appears to have been a configuration issue. Rebooting seems to have resolved the issue. Closing

**Comment by AArnott** [comment]
This rears its ugly head periodically. It's an msbuild bug. See #374
