### ISSUE TITLE
setPackageVersion: `npm version` fails for prerelease when commit appears as number with leading 0

### ISSUE THREAD

**Issue by jason-ha** [AArnott/Nerdbank.GitVersioning#415]
Example failure:
```
  Setting package version to 1.21.92-0003037965
  Error: Command failed: npm version 1.21.92-0003037965 --no-git-tag-version
  npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>] | from-git]
```
`npm version` requires <newversion> to follow semantic versioning where prerelease tags may not be a number starting with 0.

**Comment by AArnott** [comment]
Ya, this is why in certain nuget contexts we prefix with `g`. I guess we need to do so with npm as well.
Thanks for reporting.

**Comment by AArnott** [comment]
The `NpmPackageVersion` property includes `g` prefix to the commit ID to avoid this very problem. 

https://github.com/AArnott/Nerdbank.GitVersioning/blob/76f27ee306b25327ec47949cd6edc890adf9569e/src/NerdBank.GitVersioning/VersionOracle.cs#L440-L448

I wonder if you're using an old version of Nerdbank.GitVersioning? If you still see it when on the latest version, please tell me what version, and what process you used that gave you the error message.
