### ISSUE TITLE
Nerdbank.GitVersioning triggers Razor compilation without any Razor files present

### ISSUE THREAD

**Issue by rynowak** [AArnott/Nerdbank.GitVersioning#426]
### Describe the bug

A `.Views.dll` assembly is produced on build without any Razor views/content when using `Nerdbank.GitVersioning`. This isn't a big problem, but it adds an extra .5 sec or so to the build, and it could annoy people that aren't using Razor/HTML at all.

### To Reproduce

using 3.1.100

`web` at the CLI is the **empty** web template - no razor files in sight.

```sh
dotnet new web 
dotnet add package Nerdbank.GitVersioning
dotnet build
```

``` txt
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 219.83 ms for /Users/ryan/temp/temp.csproj.
  temp -> /Users/ryan/temp/bin/Debug/netcoreapp3.1/temp.dll
  temp -> /Users/ryan/temp/bin/Debug/netcoreapp3.1/temp.Views.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.48
```

### More Info

Looks to be caused by this line [here](https://github.com/AArnott/Nerdbank.GitVersioning/blob/35b087bc50864c8da8b9abfd2124f59ee31a74dd/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L246)

Because there's something in `RazorCompile` we dutifully compile it.

We can help you figure out a better solution to your needs without forcing view compilation. /cc @pranavkm

**Comment by pranavkm** [comment]
> We can help you figure out a better solution to your needs without forcing view compilation.

Might be as trivial as adding `Condition="'@(RazorGenerate->Count())' != '0'" />` to the `AddVersionFile` target

**Comment by AArnott** [comment]
Thanks for prescribing the fix. It seems to be effective.

**Comment by rynowak** [comment]
Thanks!

**Comment by japj** [comment]
FYI @AArnott this change ended up in v3.1.68, but the release notes did not mention this https://github.com/dotnet/Nerdbank.GitVersioning/releases/tag/v3.1.68

**Comment by AArnott** [comment]
Thanks for calling that out, @japj. I don't know how the github release task missed that change (or if I accidentally removed it), but I've manually edited the release to include this as a fixed bug.
