### ISSUE TITLE
Help setting version (height related) correctly on branch builds for nuget packages

### ISSUE THREAD

**Issue by comdw** [AArnott/Nerdbank.GitVersioning#435]
We're using GitVersioning in most of our projects with only one slight annoyance.  In the case of our internal NuGet packages we build pre-release versions for all branch commits and push them to nuget.   With the config we currently have unfortunately the pre-release version races ahead of our latest master, even when the branch is finally merged back to master, because of the git commit height on the branch.

Example:

- Latest master version = 3.0.17
- Start a branch
  - first commit builds/publishes version 3.0.18-g63d7b27d66
  - second commit builds/publishes version 3.0.19-g659f66fde5
  - third commit builds/publishes version 3.0.20-7c49eb8dde
  - etc
- Merge branch, master builds/publishes version 3.0.18

However the latest version of the package when pre-release versions are included ends up being shown as 3.0.20-7c49eb8dde.  Worse still, if a branch from last year had lots of commits it will be shown as the latest version even though its very old:

![image](https://user-images.githubusercontent.com/8311443/74173861-cbd08800-4c2a-11ea-8f5f-d74f86719bbe.png)

Is there a version.json configuration that will avoid this problem, possibly by pushing the git height number to a 4th semver position (giving versions like 3.0.17.1, 3.0.17.2 on the branch in the above example)?

Here's our current version.json:
```
{
    "version": "3.0",
    "nugetPackageVersion": {
      "semVer": 2
    },
    "publicReleaseRefSpec": [
      "^refs/heads/master$",
      "^refs/tags/v\\d+\\.\\d+"
    ],
    "cloudBuild": {
      "setVersionVariables": true,
      "setAllVariables": true,
      "buildNumber": {
        "enabled": true,
        "includeCommitId": {
          "when": "nonPublicReleaseOnly",
          "where": "buildMetadata"
        }
      }
    }
  }
```

**Comment by AArnott** [comment]
There is no way that _merging_ a topic branch versioned as 3.0.20 into a master branch versioned as 3.0.17 will result in master building 3.0.18. NBGV always takes the *longest* path in history, so merging 3.0.20 and 3.0.17 together will result in a 3.0.21 version.

Did you *squash* instead? That would cram all your individual commits into just one on master and result in a version height increment of just one, taking you from 3.0.17 to 3.0.18.

Don't squash commits that you've already published. There's no way for NB.GV to track history and keep versions incrementing when you do that.

**Comment by comdw** [comment]
Ok, I think this is simply because our standard workflow IS squash merge.  Publishing the pre-release builds from branch commits just helps us facilitate local testing of other apps that depend on the package (these nuget packages are not published publicly or indeed outside the dev team).  Ideally we want separate control of the version numbers on the branch, I'm feeling NBGV is not designed for this workflow (and yeah maybe we aren't following best practice for the nuget case).

**Comment by AArnott** [comment]
I would question your squash policy. Why in the world would you want to erase history of commits that you *actually published* as nuget packages? You'd never be able to find/retrieve the source for those packages again.

**Comment by comdw** [comment]
> I would question your squash policy. Why in the world would you want to erase history of commits that you _actually published_ as nuget packages? You'd never be able to find/retrieve the source for those packages again.

Put simply, its because we don't release to a public nuget feed.  Pushing the "pre-release" versions from branch commits is simply the easiest way for us to test that version against apps that consume it without merging the branch into master, i.e. its just for convenience in our dev cycle.  None of our apps ever use pre-release versions of these packages in their master/prod versions so we have no need to keep the commits or the packages for that matter  (I guess one answer is that we should delete/unlist all "invalid" pre-release versions from the nuget feed after completing the squash merge, but that's something we'd need to look at automating).

I totally understand the the expected/standard usage and that NBGV is working as designed.
