### ISSUE TITLE
GetBuildVersion fails when git history used version.json for another object

### ISSUE THREAD

**Issue by ravensorb** [AArnott/Nerdbank.GitVersioning#44]
I keep getting following when trying to use the gitversioning package

    1>Target "GetBuildVersion" in file "E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets" from project "E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\src\XLabs.Core\XLabs.Core.csproj" (target "GenerateAssemblyInfo" depends on it):
    1>Using "GetBuildVersion" task from assembly "E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.Tasks.dll".
    1>Task "GetBuildVersion"
    1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets(30,5): error MSB4018: The "GetBuildVersion" task failed unexpectedly.
    1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets(30,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
    1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets(30,5): error MSB4018:    at Nerdbank.GitVersioning.GitExtensions.GetVersionHeight(Repository repo, String repoRelativeProjectDirectory)
    1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets(30,5): error MSB4018:    at Nerdbank.GitVersioning.Tasks.GetBuildVersion.Execute()
    1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets(30,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    1>E:\Projects\Github\ravensorb\Xamarin-Forms-Labs\packages\Nerdbank.GitVersioning.1.2.1\build\Nerdbank.GitVersioning.targets(30,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
    1>Done executing task "GetBuildVersion" -- FAILED.
    1>Done building target "GetBuildVersion" in project "XLabs.Core.csproj" -- FAILED.

I have tried a rebuild all, a clean and then build, a full reboot, and still I get the same errors.

Here is the contents of my version.json file (it is at the solution level).  I have also tried at the project level and get the same result

    { "version": "2.0.5818" }

**Comment by AArnott** [comment]
I just took a look at your repo. Your [version.json file has a history of describing a different object](https://github.com/ravensorb/Xamarin-Forms-Labs/blob/master/version.json). When the MSBuild task that is failing is looking at versions in history as part of calculating your "git height", it's stumbling because you don't define a "version" field in the JSON object. I can certainly make it more resilient for cases like this -- I suppose by just ignoring the file and acting as if the it isn't there.

**Comment by AArnott** [comment]
@ravensorb: the fix for this is now available on nuget.org under version 1.2.8.

**Comment by ravensorb** [comment]
@AArnott thanks.  And yea, the version.json in the repro is from my current build process.  I was using the following on my local dev env when I was testing 

{ version : "2.0.5818" }

I'll try the new build and let you know.

Thanks again!
