### ISSUE TITLE
Support for MSBuild Core

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#56]
Target CoreCLR with the MSBuild task and reference [MSBuild Core assemblies](https://dotnet.myget.org/gallery/dotnet-buildtools).

Remaining work items:

* [x] libgit2sharp needs to be a bit smarter about adding the native binaries directory to the PATH than just to use `AppContext.BaseDirectory` because that doesn't work for an MSBuild Task that uses it.
* [x] figure out how to automate the build of a NuPkg with all the right files in place.
* [x] Load the right MSBuild Tasks assembly based on whether MSBuild is running on .NET Fx or .NET Core
* [x] Re-implement `ThisAssembly` code generation with Roslyn APIs
* [x] Get tests running again (on both net45 and .NET Core)
* [x] Get this building on appveyor
* [x] Check that NPM package contains a nbgv.nuget folder that contains a subset of what is in the nupkg rather than a bunch of facade assemblies under build\msbuildcore

To work on Linux:

* [ ] ~~Fix native libgit2 library loading in libgit2sharp~~ (https://github.com/AArnott/Nerdbank.GitVersioning/issues/112)

**Comment by AArnott** [comment]
Blocked by https://github.com/libgit2/libgit2sharp/issues/874

I'm looking into that.

**Comment by AArnott** [comment]
I've opened libgit2/libgit2sharp#1293 to track my efforts.

**Comment by AndyGerlicher** [comment]
@AArnott do you have any update you have on this? We've merged our change using this to our .net core branch and need to figure out what we should do.

**Comment by AArnott** [comment]
The latest news is here: https://github.com/libgit2/libgit2sharp/pull/1318

In short, the work to make libgit2 portable is basically complete. But we need to get it to work in the xplat CIs. I'm OOF for the next 2.5 weeks, so hopefully @ethomson will be able to make progress.

**Comment by piotrpMSFT** [comment]
Any updates on when a .NET Core version might be available?

**Comment by asherber** [comment]
I'm also interested in this.

**Comment by AArnott** [comment]
I've resumed work on this with a private build of the libgit2sharp package that supports netstandard pushed to myget.

**Comment by AArnott** [comment]
Snagged by https://github.com/dotnet/sdk/issues/705

**Comment by onovotny** [comment]
Nice catch!

**Comment by AArnott** [comment]
I might work around it by publishing a package to myget with an alternate identity.

**Comment by AArnott** [comment]
Alright: I've hacked together a NuGet package that works on `dotnet build`. I tested on Windows, but I *believe* it will work on other operating systems as well.

**Comment by AArnott** [comment]
OK, I have a semi-supportable package for folks to use:

nuget feed: https://www.myget.org/F/aarnott/api/v2/package
package version: 1.6.1-beta-g4dc3644c72

Of course later versions in the 1.6.x family are probably better when they become available.
