### ISSUE TITLE
Conflicting target names with Microsoft.XmlSerializer.Generator

### ISSUE THREAD

**Issue by mkaring** [AArnott/Nerdbank.GitVersioning#698]
Hello,

I encountered an issue when using `Nerdbank.GitVersioning` along with `Microsoft.XmlSerializer.Generator`.

For reference this is the project file, causing the issue:
```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.XmlSerializer.Generator" Version="6.0.0" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.4.244">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
```

This file causes the issue, both for Visual Basic as well as for C# projects. There are no code files required in the project to trigger the issue.

The error raised is an `FileNotFoundException` that is looking for the output assembly. The responsible target is called before the actual build step is executed.
Now the reason for this is the [`GenerateAssemblyVersionInfo` target](https://github.com/dotnet/Nerdbank.GitVersioning/blob/v3.4.244/src/Nerdbank.GitVersioning.Tasks/build/Nerdbank.GitVersioning.targets#L139). `Nerdbank.GitVersioning` registers this target to be executed ahead of the build.
`Microsoft.XmlSerializer.Generator` registers an target [with the exact same name](https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/Microsoft.XmlSerializer.Generator/src/build/Microsoft.XmlSerializer.Generator.targets#L33) to be executed after the build is done.

Now the result is that the version of the XmlSerializer Generator is called at the time GitVersioning requests it. This results in the error, because the expected output file is not build yet.

Is there any chance to rename this target in `Nerdbank.GitVersioning` to resolve the conflict?

**Comment by AArnott** [comment]
Ooh boy. Yes, I suppose we should, although it may be disruptive to some users. Thanks for reporting.
