### ISSUE TITLE
Support OS X with Xamarin Studio

### ISSUE THREAD

**Issue by arlm** [AArnott/Nerdbank.GitVersioning#88]
Unfortunately the native part does not work :(

/Volumes/data/git/pinvoke/src/packages/Nerdbank.GitVersioning.1.5.46/build/NerdBank.GitVersioning.targets: Error: Error executing task Nerdbank.GitVersioning.Tasks.GetBuildVersion: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. (CodeGeneration).

I'll take a look into it in the future to help. For now I'll just disable that on my machine.

**Comment by AArnott** [comment]
Dupe of #56
