### ISSUE TITLE
Enable controlling the length of git commit in the version number

### ISSUE THREAD

**Issue by IlyaBiryukov** [AArnott/Nerdbank.GitVersioning#89]
Right now it is hard-coded to 10 characters. It may be too long in some scenarios. If we can control that from version.json, that would be awesome.

**Comment by AArnott** [comment]
Interesting. When is it too long?

**Comment by IlyaBiryukov** [comment]
Nuget version is limited to 20 characters.

**Comment by IlyaBiryukov** [comment]
See https://github.com/NuGet/NuGet.Client/pull/571/files

**Comment by AArnott** [comment]
I see. So as long as our generated -prerelease version length does not exceed 20 characters we should be fine. Since we have a dedicated property for nuget package versions, we can reduce git commit ID length automatically to make it fit.
When did you hit this? With particularly long integer values or due to a long -prerelease tag you define yourself that was added to the git commit id?

**Comment by AArnott** [comment]
@heaths mentioned wanting this too.

We should emit a build warning when the short commit ID length prescribed is not long enough to unambiguously identify the commit.
Determining the minimum length required to uniquely id a commit is documented here: http://stackoverflow.com/questions/16413373/git-get-short-hash-from-regular-hash
From that, I think the revparse method in libgit2sharp (that should be easy to find) probably takes the parameters that are shown in the command line.

**Comment by ctaggart** [comment]
Would it be best to allow git (libgit2) to control the length of the short commit ID? It figures out what length it should be. I was expecting these two things to match:

```
PS C:\Users\taggac\github\SourceLink> nbgv get-version -f json | ConvertFrom-Json | select -ExpandProperty GitCommitIdShort
30b8743de7
PS C:\Users\taggac\github\SourceLink> git rev-parse --short HEAD
30b8743
```

The length for the git short would then be controlled by the git settings.
https://git-scm.com/docs/git-config#git-config-coreabbrev

**Comment by AArnott** [comment]
Interesting idea. For cli scenarios that sounds great. But for versions built into a file, we should set an explicit minimum. Because even if 4 characters provide a unique commit id today, they won't after a thousand more commits are added.

**Comment by ctaggart** [comment]
By default it is set to `auto` which usually amounts to 7 characters for me and matches what GitHub shows.

**Comment by ctaggart** [comment]
@AArnott any more thoughts on this before I attempt it?

**Comment by AArnott** [comment]
Thanks for your PR @ctaggart. Reviewing your PR I think I need to understand the goals/requirements a bit more. So can you tell me what your interest is in shortening this?

A potential problem I see with letting git determine the length is non-deterministic builds:
1. it may vary based on machine/user configuration
1. it may grow over time for the same commit as more git objects are added to the database

NB.GV prioritizes build reproducibility, so assuming either or both of the above are true, I think our best plan for shortening the git commit ID is to do one or both of these:

1. Control the length via a property in the `version.json` file
1. Shorten the length automatically as necessary to keep the overall length of the version under some limit.

But to know which of these are more appropriate, I'd like to better understand what your motivation is for having the fix.

**Comment by ctaggart** [comment]
Based on your feedback, I updated the pull request #304 to 

> Control the length via a property in the version.json file

It default to 10, which is the current default.

The builds should still use the full commit, so they should be deterministic, right? I want the package suffix to match what is seen in GitHub to make it easier to locate the package. I understand that the git height is changing each time.

**Comment by AArnott** [comment]
>  I want the package suffix to match what is seen in GitHub to make it easier to locate the package.

So you want the commit ID part of a version that appears on nuget.org (something like this):

![image](https://user-images.githubusercontent.com/3548/54150816-a887d200-43f6-11e9-92c0-d06e79f3f3f3.png)

to closely resemble a commit ID that GitHub shows like this:

![image](https://user-images.githubusercontent.com/3548/54150670-40d18700-43f6-11e9-9742-1a4c810ab622.png)

Is that right? If so, and if github's commit id length varies, then hard-coding it to a fixed length less than 10 wouldn't always match github's length. Is that a problem? If so, perhaps the setting in version.json should allow specifying a fixed length (as you've done) and also offer opting in to a non-deterministic commit ID length for [NuGet package versions](https://github.com/AArnott/Nerdbank.GitVersioning/blob/35aea93f669bea81e51758e49d8e7b392df84e1d/src/NerdBank.GitVersioning/VersionOptions.cs#L263) as well.

Thoughts?

**Comment by ctaggart** [comment]
https://github.com/AArnott/Nerdbank.GitVersioning/pull/304/files#diff-8aa8df28c84262be5809f3de55d83688R104 is `repo.ObjectDatabase.ShortenObjectId(commit, gitCommitIdShortLength)`, which is actually a minimum length. When there is not a git repo present, it is a simple truncate. Does it make sense to have two different settings?

**Comment by ctaggart** [comment]
What about this?
- `gitCommitIdShortFixedLength` default of `10`
- `gitCommitIdShortAutoMinimum` default of `0`. Something higher than 0 opts into using the git commit abbreviation based on the number of git objects [as documented](https://forum.openwrt.org/t/git-2-11-and-commit-hash-abbrev-length/532).

**Comment by AArnott** [comment]
Hmmm.. so it does erode the deterministic build requirement. This value can go not just into nuget package versions, but also into the C# compiler. For example this line is injected into the version.cs file generated by NB.GV:

```cs
    internal const string AssemblyInformationalVersion = "2.1.6-alpha+488de4b70e";
```

So if over time the same commit has varying lengths for the commit ID, then that means the compiler inputs change and then PDB/DLL MVIDs don't match, as just one example of a problem from non-deterministic builds.

Thanks for the link to the script for getting stats on git object id length. That was certainly interesting.

I'd rather not have _two_ integer properties that compete with each other (where one property is effective till the other is set to certain ranges). But I can't think of a better option. So your fixed/auto proposal sounds like a good compromise. Can you be sure to update the schema.json file and adequately document these new properties there?

**Comment by ctaggart** [comment]
> Can you be sure to update the schema.json file and adequately document these new properties there?

Yes, I'll update `schema.json`. 

For `AssemblyInformationalVersion`, I'd prefer that it uses the [full commit like dotnet sourcelink does](https://github.com/dotnet/sourcelink#prerequisites-for-net-projects).

**Comment by AArnott** [comment]
> For AssemblyInformationalVersion, I'd prefer that it uses the full commit like dotnet sourcelink does.

That's probably worth an issue of its own if you'd like to pursue that. I think that makes the assembly informational version unwieldly in length, but it would help resolve one of the determinism problems so I'm open to considering it.

**Comment by ctaggart** [comment]
Yes, I think that a full length git commit in AssemblyInformationalVersion can be a separate issue.

#304 has been updated based on your feedback and is ready for another review.
