### ISSUE TITLE
Better integration with VS2017 SDK builds

### ISSUE THREAD

**Issue by AArnott** [AArnott/Nerdbank.GitVersioning#93]
This issue tracks the work (in and out of this project) to get Nerdbank.GitVersioning to integrate well with the new project type introduced by the .NET Core project templates in Visual Studio 2017.

**Comment by AArnott** [comment]
Starting with [1.5.61](http://www.nuget.org/packages/Nerdbank.GitVersioning/1.5.61) Nerdbank.GitVersioning can successfully perform its functions on the SDK builds of .NET assemblies.

However, the new `/t:Pack` target of [these projects do not import any referenced NuGet packages' MSBuild files](https://github.com/dotnet/sdk/issues/530). So we can't yet set the version of the NuGet packages built with the Pack target.

**Comment by onovotny** [comment]
Part of this should include creating netcoreapp1.0/netstandard version of the task using the coreclr msbuild targets so that it can work with `dotnet build` and not just msbuild.

**Comment by AArnott** [comment]
The package version is fixed by 584f78967a446d30e6bc85f063bbcad2878a61d2.

@onovotny: #56 already tracks .NET Core support.
