### ISSUE TITLE
Support for native binaries?

### ISSUE THREAD

**Issue by jazzdelightsme** [AArnott/Nerdbank.GitVersioning#94]
I've got a .sln with both native (C/C++) and managed (C# and C++/CLI) projects. It would be great to also be able to stamp the native binaries with the same version information as the managed binaries. I'm not sure what the best way to implement this would be... perhaps to generate a .rc file, or to produce the .res file directly.

**Comment by AArnott** [comment]
Ooh,  that's interesting. I'd be very interested in a pull request on this if someone can do it.

**Comment by heaths** [comment]
I've got a pattern I can generalize and work on a code change here.

**Comment by AArnott** [comment]
Thanks, @heaths

**Comment by jazzdelightsme** [comment]
Cool!

I happen to have some self-contained C# code that can emit a .res file containing version information (VS_FIXEDFILEINFO et al). I've used it in other, managed code projects where you couldn't depend on having rc.exe to compile a .rc to a .res. For an actual native code project, you _could_ depend on being able to compile an .rc, but if I were to try to do this change, I don't know that it would be any less annoying to codegen a .rc file than it would to just create the .res file, given that I know how and already have code to do the latter. Also, since link.exe can accept multiple .res files, it's not a composition problem like it is for managed code (with csc.exe, you get one /win32res:file).

But after snooping around this project (NBGV) a bit, I've come to the conclusion that my msbuild-fu is far too weak, and given the amount of vacation time I have left, I don't think I'd be able to get very far. But @heaths, you are welcome to the .res-generating code if it is useful at all.

If generating the .res directly is interesting, another thought I had is maybe the .res-emitting code could/should be its own nuget package, since it's potentially useful in other projects. I could probably scrape that together.

Code here: https://gist.github.com/jazzdelightsme/844a5e6b97a58148767e01eb6dac5c9b

**Comment by AArnott** [comment]
Personally, I favor NB.GV generating source code rather than a binary file so that folks can see what effect it's having on the build more clearly.

**Comment by heaths** [comment]
My plan is to generate source, yes. It can be combined with other resources in the RC file and be used as variables in code.

- Heath via Nine<http://www.9folders.com/> on Android
________________________________

**Comment by AArnott** [comment]
Sweet!

**Comment by heaths** [comment]
Seems we shouldn't close this until I merge my script changes with @robmen's changes to just support this. Right now, manual edits will be necessary unlike _csproj_ or _vbproj_ files.

**Comment by AArnott** [comment]
@heaths are you talking about scripts to remove hard-coded versions from the project? 
I don't consider those mandatory. And in fact modern nuget client scenarios like PackageReference and project.json don't execute those scripts anyway. 
I'm willing to add the feature, but that would be a bonus rather than mandatory for this issue.
